### ISSUE TITLE
TypeError: 'undefined' is not an object (evaluating 'obj.css') at undefined:213

### ISSUE THREAD

**Issue by aganglada** [webpack-contrib/style-loader#100]
I'm running test with karma and webpack and it's throwing an error saying:

npm run test:watch

> invoice@1.0.0 test:watch /Users/agarcia/Projects/test
> NODE_ENV=dev karma start karma.config.js --auto-watch --no-single-run

PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  TypeError: 'undefined' is not an object (evaluating 'obj.css') at undefined:213

PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.154 secs / 0 secs)
I've looked into the project to see from where this 'obj.css' is coming, there is no file called obj.css but in style-loader there are some conditions where they are using obj.css.

Did anyone of you have this problem before?

I already update style-loader to the last version, but no success.

Thanks in advance!

**Comment by scottwio** [comment]
Got the same issue @aganglada did you ever find a solution?

**Comment by aganglada** [comment]
@scottwio it´s because of the sass-loader doesn't work with karma-webpack plugin, I commented the css inside the js and it works.

**Comment by ttbarnes** [comment]
Same issue here. Commenting out the sass imports it works, but this is not feasible for large scale projects with many components/sass files or running automated tests for example.

**Comment by ttbarnes** [comment]
A workaround solution: 

You can pass an arg in your npm scripts eg declaring `--sass=false`, and then from webpack config, push the style loader to your loaders depending on the sass arg.

**Comment by michael-ciniawsky** [comment]
Please reopen in `karma-webpack` && `sass-loader` and if anything related to `style-loader` should cause regressions feel free to reopen Thx 😛
