### ISSUE TITLE
Call URL.revokeObjectURL() after stylesheet loaded

### ISSUE THREAD

**Issue by OpenGG** [webpack-contrib/style-loader#104]
To load stylesheets, Style loader creates object urls, and feeds them to `<link>` elements. Those object urls will be revoked only when their own related stylesheet get removed or updated.

But keeping references to object urls is not that necessary really, once they got loaded into `<link>`, you can call `URL.revokeObjectURL(url)` right away, while the style rules still apply.

See this demo for details.

https://jsfiddle.net/8oee3yex/4/

**Comment by OpenGG** [comment]
Detecting `<link>` loading status could be tricky: http://www.phpied.com/when-is-a-stylesheet-really-loaded/

Bug for those browsers dont supported `onload` event on `<link>`, it is not that big a deal, we simply dont call `URL.revokeObjectURL(url)`, due to the lack of detecting method.

**Comment by michael-ciniawsky** [comment]
Please reopen this in https://github.com/webpack-contrib/restyle-loader 😛
