### ISSUE TITLE
paths option

### ISSUE THREAD

**Issue by danielb2** [webpack-contrib/style-loader#106]
Is it possible to have a paths option to tell `@import` where to load files relative to?

Currently because of how npm installs handles it, it can be difficult to get this configured with the correct paths ( my case is having a dependency for another module )

stylus-loader uses a `paths` option. is someting like this possible for this loader?

**Comment by michael-ciniawsky** [comment]
@danielb2 Can you provide an example for this please, I'm not sure if I fully understand what you whatt to achieve here. Is it for `@import https://path/to/import.css` ?

**Comment by danielb2** [comment]
it's been 1 year, 1 month and 12 days since I filed this. I have no idea about this, and it's not useful for me anymore
