### ISSUE TITLE
HMR with reference counting API

### ISSUE THREAD

**Issue by geekyme** [webpack-contrib/style-loader#113]
I'm using the reference counting API for CSS modules in a react component

```
import styles from './Testing.styl';
...
componentWillMount() {
    styles.use();
  }

  componentWillUnmount() {
    styles.unuse();
  }

  render() {
     return <div className={ styles.locals.category }>Test </div>;
  }

```

When I change `Testing.styl`, I get a build error: 
`TypeError: Cannot read property 'category' of undefined`

This only happens when I am using the reference counting API.

**Comment by geekyme** [comment]
It looks like the `locals` in the imported style module is missing on a hot reload.

```
Object {}ref: ()unref: ()unuse: ()use: ()
```

**Comment by michael-ciniawsky** [comment]
@geekyme Can you please setup a test repo to investigate further?

**Comment by michael-ciniawsky** [comment]
@geekyme  If you still have this regression, see the previous comment and feel free to reopen 😛
