### ISSUE TITLE
Blob links affects the styles later than JS execution

### ISSUE THREAD

**Issue by ipy** [webpack-contrib/style-loader#121]
html:

```
  <style type="text/css">
  .test {
    background: red;
    width: 100px;
    height: 100px;
  }
  </style>
  <div class="test"></div>
```

css:

```
.test {
  display: none;
}
```

js:

```
require('./test.css');
$('.test').show();
```

In this case, if css-loader is used with ?sourceMap option, the css will be generated as Blobs. However, it seems that it will take sometime for blob link to load. So `$('.test').show();` executes before `display: none;` takes effect, and nothing shows up.
It's fine to print css directly on the page.

Is there any way to enable source-map without that problem?

**Comment by Lihuanghe** [comment]
this may cause by  a bug of chrome.
ref:
https://www.nccgroup.trust/uk/about-us/newsroom-and-events/blogs/2016/february/script-injected-css-will-no-longer-block-rendering-in-chrome/
https://bugs.chromium.org/p/chromium/issues/detail?id=571725

resolve:
```
require('./test.css');
setTimeout(function(){
	$('.test').show();
},0)

```

**Comment by elisechant** [comment]
this is annoying, currently my solution is to do a programmatic setTimeout to delay JavaScript execution which is gross.

**Comment by fmatoss** [comment]
I have this issue too, after doing some research, I found that there was a bug preventing source maps in `<style>` tag from working, but it's working now for me in Chrome 56.

Relevant links:
https://github.com/webpack-contrib/style-loader/issues/30#issuecomment-61066831
https://bugs.chromium.org/p/chromium/issues/detail?id=456062

This probably would fix the relative path in `publicUrl` with source maps as well.

**Comment by ekulabuhov** [comment]
There's a planned feature for vNext of the style-loader that will potentially solve this problem. If you're still experiencing this issue could you give it a go and report back on whether it helps? Thank you!

PR: #165

**Comment by michael-ciniawsky** [comment]
#219 will fix this, but there is not current timeline when this land, so please be patient :)

**Comment by galvarez421** [comment]
I am experiencing a potentially related issue. Given a file like this:

styles.js:

```
import 'bootstrap.scss';
import 'app.scss';
```

I can see in the `<head>` that the Blob links are inserted in the correct order, however the computed styles in Chrome dev tools do not reflect this. For example, if I set an `<h2>` style in app.scss, the style will not take precedence over a Bootstrap h2 style even though it should (same specificity, but style declared in subsequent link). Perhaps the Bootstrap styles are interpreted as being after my app styles if the Bootstrap styles finish loading after the app styles do?... Or are stylesheet links not guaranteed to execute in order?
