### ISSUE TITLE
HMR fail only when 'css' and 'style' loaders used

### ISSUE THREAD

**Issue by waterstar** [webpack-contrib/style-loader#127]
The error message is the well reported - "webpack{hash}.hot-update.json 404 (Not Found)". However for my case, it is unlikely the "publicPath" issue as it is working when css related loaders aren't used. My Backend setup is Sails with "webpack-dev and hot-middleware". Could this be a bug when these modules are used together?  Thanks.

```
{ test: /\.css$/, loader: 'style!css' }

```

**Comment by michael-ciniawsky** [comment]
@waterstar Please provide more info (`webpack.config.js`, `package.json`) etc. Also ensure to use the latest `style-loader`

**Comment by michael-ciniawsky** [comment]
@waterstar If you still have this regression, see the previous comments and feel free to reopen 😛

**Comment by AdamWillden** [comment]
@waterstar I know this issue is old but I too have a webpack config that acts only on `.scss` files and I also get the hot reload 404. 

Did you manage to get such a setup working without the 404?
