### ISSUE TITLE
insertAt shadow root?

### ISSUE THREAD

**Issue by am80l** [webpack-contrib/style-loader#131]
I'm curious if this community has given any thought to use cases involving shadow elements.

What I'm envisioning is a capability that would allow you to inject styles into a shadow root, as opposed to just the head of the document, thereby preserving encapsulation for a given component.

I am admittedly new to web components, but using css loader to inject encapsulated styles into shadow elements just sounds like an awesome capability :) 

Anyone given thought to this use case?

Thanks!

**Comment by ahstro** [comment]
I need this myself, and I'm working on a solution using a new option called `insertInto`, which will take a CSS selector to call `document.querySelector` with. This could allow you to insert the styles into the ShadowDOM using a `#host::shadow #someElement`-selector, if it exits prior to style-loader running (which is the part I'm having trouble with).

**Comment by michael-ciniawsky** [comment]
Fixed by #135
