### ISSUE TITLE
Throw earlier for non-browser environment

### ISSUE THREAD

**Issue by mohsen1** [webpack-contrib/style-loader#136]
[this line](https://github.com/webpack/style-loader/blob/master/addStyles.js#L14) runs before [this line](https://github.com/webpack/style-loader/blob/master/addStyles.js#L25) that throws `"The style-loader cannot be used in a non-browser environment"`.

**Comment by ahstro** [comment]
How? I might be reading it wrong, but it looks to me like the `throw`-line runs first thing in the loader, while the line you're pointing to is just a declaration of a function that is called [a few lines below](https://github.com/webpack/style-loader/blob/master/addStyles.js#L31)?

**Comment by mohsen1** [comment]
I didn't study the code very closely. Maybe I'm wrong but the error I was getting wasn't the thrown error I mentioned

**Comment by ahstro** [comment]
I'm no expert at all, so I'm only guessing, but I think that the `non-browser`-error is only thrown if you're in some sort of debug mode. Maybe you were in in release or just undefined mode (no idea how one would define a mode to begin with)

**Comment by michael-ciniawsky** [comment]
According to #159 (last comment) any kind SSR(-ish) support in `style-loader` will be rejected in the future, `style-loader` will only work within the browser. For SSR(-ish) solutions also see #159 Thx 😛
