### ISSUE TITLE
Can style-loader be added as an external?

### ISSUE THREAD

**Issue by mikehdt** [webpack-contrib/style-loader#138]
Hi, I'm working on a project which uses an NPM enterprise server to distribute and handle different modules which are then compiled by a host module. Keeping the module sizes down and avoiding duplicate bundled code is important for us.

At the moment, I've got our common code set up to use WebPack's `externals` feature to avoid duplicate code. However, in investigating why individual modules were still rather large in size, I've found a lot of repeated code in each is coming from `style-loader`, doing its job of (naturally) injecting styles into the page when the module loads.

I'm guessing because this is a WebPack Loader, rather than an explicit JS `import`, that this may need to be treated differently. Is there a way to de-duplicate this code so that there is only one copy being included, or is this not possible (at least for the common functions; from what I can tell it creates separate functions for actual CSS being injected as one would expect)?

As an example, these functions: https://github.com/webpack/style-loader/blob/master/addStyles.js amongst others are all being repeatedly included, and it would seem that methods which are generalised could hopefully be de-duplicated somehow.

Thanks for your time and great efforts :)

**Comment by zhenghao-lee** [comment]
the same problem.

**Comment by zhenghao-lee** [comment]
use plugin “extract-text-webpack-plugin”

**Comment by michael-ciniawsky** [comment]
@mikehdt For production please use `extract-text-webpack-plugin` instead, where you get the clean CSS extracted from the bundle into a separate file (parallel loading), while I agree that there maybe ways to dedupe, `style-loader` is more for development proposes and this has not high priority atm.
If you have something in mind please feel free to propose a solution via PR/Gist, I'm closing this for now, but in case I missed something please feel free to reopen 😛
