### ISSUE TITLE
Loader strips out "/" character when inserting

### ISSUE THREAD

**Issue by CrashyBang** [webpack-contrib/style-loader#139]
I am trying to use the `hack` framework: https://github.com/egoist/hack

Which takes advantage of the `\` syntax for example: `.cell\-4of12`.

However when the css is inserted it is converted over to: `.cell.-4of12`.

This results in an `Unknown word` error, here is a quick demo showing that the code does fail: http://codepen.io/crashy/pen/BzqjRk

Has this come up before is there anyway round this?

Cheers,
Otis.

**Comment by michael-ciniawsky** [comment]
@CrashyBang This maybe related to `css-loader` if this is still relevant, in any case I need more info (`webpack.config.js`, `package.json`) etc.

**Comment by michael-ciniawsky** [comment]
@CrashyBang If you still have this regression, see my previous comment and feel free to reopen 😛
