### ISSUE TITLE
load css with media=all attribute

### ISSUE THREAD

**Issue by tnrich** [webpack-contrib/style-loader#147]
Hey there,

I initially posted the following issue to: https://github.com/webpack/css-loader/issues/294
Someone told me I would be better served posting it here instead. Do you think you can help me? 
Here is the issue:

I'd like to add the media=all attribute to the css files that webpack is generating:
![image](https://cloud.githubusercontent.com/assets/2730609/16501750/d720e1a4-3ebf-11e6-8e19-7497811c7d97.png)

The reason for this is because the css is not being used when I try to print my webpack-generated webpage. 

Thanks for the help!

**Comment by elektronik2k5** [comment]
@tnrich, it looks like the attribute can be easily added here: https://github.com/webpack/style-loader/blob/9dc45a6dee16553a64071031d18feb1562df86a2/addStyleUrl.js#L12 
I suggest makeing a PR to suppor this. I'd make it optional via a loader `query` (webpack1 term) or `option` (webpack2 term).

**Comment by felixmosh** [comment]
@elektronik2k5, i think that i should be [here](https://github.com/webpack/style-loader/blob/9dc45a6dee16553a64071031d18feb1562df86a2/addStyles.js#L130)

**Comment by michael-ciniawsky** [comment]
Will be fixed by #155

**Comment by viksit** [comment]
@tnrich @felixmosh I'm trying to use this functionality with  "css-loader": "0.26.1" /   "style-loader": "0.13.1".

My webpack config looks like,

```
{
        test: /\.css$/,
              loaders: [
          'style-loader?sourceMap&{attrs:{id: "style-id-1"}}',
          'css-loader?modules&importLoaders=1&localIdentName=[name]___[local]'
        ]
      },
```

but I'm unable to see a new ID tag being added. Could someone advise on 

a) how to use this feature in the loader format I'm using above and
b) how would I find the right version this appears in, in case I'm on something older?

**Comment by michael-ciniawsky** [comment]
@viksit `attrs`is unreleased in `style-loader`, could you try by installing from git directly meanwhile? 

**package.json**
```
{
   "devDependencies": {
      "style-loader": "webpack-contrib/style-loader"
    }
}
```

**Comment by felixmosh** [comment]
BTW, it suppose to be a json.

**Comment by michael-ciniawsky** [comment]
@felixmosh 👍  Ohh...yep @viksit  `{ attrs: { id: "style-id-1" }} => { "attrs": { "id":  "style-id-1" }}`

**Comment by viksit** [comment]
Hmm, so I did the following but still no luck. @michael-ciniawsky @felixmosh 


```
"devDependencies": {
  ...
      "style-loader": "webpack-contrib/style-loader",
...
}
```

```
rm -rf node_modules/style-loader
npm install

`-- style-loader@0.13.2  (git://github.com/webpack-contrib/style-loader.git#1ae44f8c86749a4c0d7d07d4466b873cab72b0f4)
  `-- loader-utils@1.0.3

```

and then,

```
{
        test: /\.css$/,
        loaders: [
          'style-loader?sourceMap&{"attrs":{"id":"style-id-1"}}',
          'css-loader?modules&importLoaders=1&localIdentName=MyApp___[local]'
        ]
      },
```

but still,

```
> document.getElementById('#style-id-1')
< null
```


![image](https://cloud.githubusercontent.com/assets/198669/23871746/e34bfa84-07e8-11e7-9445-12c741bacda8.png)

**Comment by michael-ciniawsky** [comment]
Maybe `{"attrs":{"id":"style-id-1"}} => &attrs={ "id": "style-id-1" }` not 💯 I'm using webpack 2 😛

**Comment by michael-ciniawsky** [comment]
mom

**Comment by viksit** [comment]
@michael-ciniawsky aaahhh. ok, is that what I should move to? (webpack 2?). I'm so new to react, I started with a template from the fb team which seems to use wp1(!).

I'll try this with webpack 1.14 in the meantime.

**Comment by felixmosh** [comment]
@viksit, pay attention that the params mechanism in webpack works either with queryString or with an object....
You used both.
Try that:
```
'style-loader?{"sourceMap":true,"attrs":{"id":"style-id-1"}}',
```

**Comment by viksit** [comment]
@felixmosh ah. I didn't realize that was the case - many thanks for the pointer, this works now.

**Comment by michael-ciniawsky** [comment]
@felixmosh Yep like that, thx very much 👍
