### ISSUE TITLE
Access styles at runtime

### ISSUE THREAD

**Issue by marvinhagemeister** [webpack-contrib/style-loader#152]
We are currently using a react-based styleguide called [react-styleguidist](https://github.com/styleguidist/react-styleguidist) which basically acts as a shell for custom components. Being based on webpack the styleguide-app itself makes heavy use of webpack and style-loader.

Now we have our first component where we need `position: fixed`. Elements with position fixed obviously don't respect the container boundaries and are positioned relative to the viewport or iframe boundaries. The latter solves our issue and I have a fork (PR) nearly done where each component is dynamically rendered into an `<iframe/>`.

As expected, `style-loader` appends `<style>`-tags to the parent window. Due to the nature of an iframe, the elements lack any styling, because the style tags are not in the same scope.

I'm currently stuck. Is there a way to be able to access the compiled css?

**Comment by michael-ciniawsky** [comment]
@marvinhagemeister Would #146 suit your needs?

**Comment by ekulabuhov** [comment]
I don't fully understand the problem here. @marvinhagemeister could you clarify if you need to modify your css to remove `position: fixed` OR do you want to insert your styles into an iframe? If latter, #135 seems like a solution for you?

**Comment by michael-ciniawsky** [comment]
Fixed by #135
