### ISSUE TITLE
Can I use url and useable together?

### ISSUE THREAD

**Issue by mrdulin** [webpack-contrib/style-loader#158]
```js
{
				test: /\.css$/,
				include: [path.join(__dirname, '/src/test.useable.css')],
				loader: 'style-loader/url/useable!file-loader'
			}
```

```bash
ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'style-loader/url/useable' in /Users/dulin/workspace/webpack-summer/style-loader/src
 @ ./src/index.js 7:16-45
```

it seems not work.

**Comment by NukaPunk** [comment]
I'm not sure, but it looks like you should have `/url` switched to `url-loader` (and make sure it's installed).

``` Javascript
{
    test: /\.css$/,
    include: [path.join(__dirname, '/src/test.useable.css')],
    loader: 'style-loader/useable!url-loader!file-loader'
}
```

**Comment by michael-ciniawsky** [comment]
@mrdulin @NukaPunk Could one of you  please confirm if the solution with `url-loader` works, I doubt it to be honest 😛 . @mrdulin The problem it that `style-loader/url/useable` isn't a module, maybe 

`style-loader/url!style-loader/useable!...` 

but untested if that conflicts somehwere

**Comment by michael-ciniawsky** [comment]
@mrdulin @NukaPunk If my last post didn't bring any results feel free to reopen anytime 😛

**Comment by NukaPunk** [comment]
No I think you are correct @michael-ciniawsky , `style-loader/url/useable` isn't a module.

In my answer my assumption was that @mrdulin was looking for a way to chain `style-loader/useable` with `url-loader`. If this is incorrect let me know and I can try to be of more help.

**Comment by michael-ciniawsky** [comment]
@NukaPunk Still confused by what is the actual usecase and if `url/file-loader`are compatible at all 😛. I think  `raw-loader` is the better solution here `use: [ style-loader', 'raw-loader' ]` to convert the CSS String into a module and let style-loader add it to the DOM or if the file doesn't need any tranformation or a component is depending on it during build time just add a `<link>` in the `index.html`

**Comment by utlime** [comment]
Hey @michael-ciniawsky,
could you please reopen this issue. I have the same problem, I created question on stackoverflow, but seems no answers =\
https://stackoverflow.com/questions/56966623/how-to-use-style-loader-useable-and-style-loader-url-together
