### ISSUE TITLE
duplicate css code in different styles

### ISSUE THREAD

**Issue by nanjixiong218** [webpack-contrib/style-loader#161]
**Do you want to request a *feature* or report a *bug*?**

no
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
I want duplicate the css code in different styles,
when use singleton option , the css have the same code，can style-loader do some duplicate and expose a option？

![image](https://cloud.githubusercontent.com/assets/5085933/21837840/98f6e8c2-d809-11e6-8ecc-1e7817933a9a.png)

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

**Comment by phun-ky** [comment]
I have the same issue, and I have this config for dev:

    const config = {
      postcss: () => {
        return [
          cssnano
        ];
      },
      stylus: {
        preferPathResolver: 'webpack',
        use: [
          poststylus([
            autoprefixer({browsers: 'last 2 versions, > 1%'})
          ])
        ]
      },
      stylint: JSON.parse(fs.readFileSync(path.join(__dirname, '../../.stylintrc'), 'utf-8')),
      module: {
        preLoaders: [{
          test: test_expressions.stylus,
          loader: 'stylint'
        }
        loaders: [{
          test: test_expressions.css,
          loader: 'style?singleton=true!css?minimize=true'
        },{
          test: test_expressions.stylus,
          loader: 'style-loader?singleton=true!css-loader?minimize=true!postcss-loader!stylus-loader'
        }]
      }
    };

I have jsx components that imports their respective `*.styl` file, and in those respective files, they each `@require/@import` files like `button.styl` and `spacing.styl` to be able to `@extend .className`.

This results in a duplication that is equal to the number of total imports of a `*.styl` file, i.e. `button.styl`, resulting in everything from 2 equal declarations to n+1 equal declarations.

**Comment by phun-ky** [comment]
While the original issue here is related to sass/less/stylus, a fix/hack/patch for this is to use the `optimize-css-assets-webpack-plugin` in conjunction with `extract-text-webpack-plugin` to produce, like this: https://gist.github.com/phun-ky/766e5ec9f75eac61c945273a951f0c0b. 

If you want to use this in dev, you will have to use a plugin like `write-file-webpack-plugin` to force webpack to write the file to disk in dev.

**Comment by michael-ciniawsky** [comment]
@nanjixiong218 Please see @phun-ky comment. @phun-ky Thx 👍
