### ISSUE TITLE
Angular 2 Universal "window is not defined" error.

### ISSUE THREAD

**Issue by epanchintsev** [webpack-contrib/style-loader#167]
When using with Angular 2Universal retrieve error "Call to Node module failed with error: Prerendering failed because of error: ReferenceError: window is not defined".  
Obviouse error caused by using window object in that fragment of style-loader
```
isOldIE = memoize(function() {
			return /msie [6-9]\b/.test(window.navigator.userAgent.toLowerCase());
		})

```

**Comment by UnGast** [comment]
I also experienced this with vue-server-renderer.

**Comment by leobudima** [comment]
Same problem with React...

**Comment by UnGast** [comment]
#159

**Comment by michael-ciniawsky** [comment]
@epanchintsev @UnGast @leobudima I'm sry you guys but `style-loader` won't support any SSR functionality and therefore this issue is sadly won't fix. See #159 for reasons and solutions/alternatives
