### ISSUE TITLE
URL option with css!postcss!less loaders

### ISSUE THREAD

**Issue by danielverejan** [webpack-contrib/style-loader#171]
How can I use the URL option with other loaders?

I have this configuration
```
{
    test: /\.(css|less)$/,
    loader: 'style/url!file?name=css/[name].css!css?importLoaders=2!postcss!less-loader',
},
```
In a js file I require a index.less file, style loader adds a link like this
`<link rel="stylesheet" type="text/css" href="/localPath/Build/css/index.css">`

but it's content looks like this
```
exports = module.exports = require("./../node_modules/css-loader/lib/css-base.js")();
// imports


// module
exports.push([module.id, "CSS CONTENT IS HERE", ""]);

// exports
```
What am I doing wrong?

**Comment by michael-ciniawsky** [comment]
@danielverejan Is this resolved by `restyle-loader` 😜 ? If it isn't please reopen
