### ISSUE TITLE
Breaks in node 0.12

### ISSUE THREAD

**Issue by Alspaladin** [webpack-contrib/style-loader#178]
Version 0.13.2
Bug

Current version breaks in node v0.12 because of dependency update:
loader-utils from v0.2.7 to v1.0.2, which is compatible only with node >=4.0.0

**Comment by michael-ciniawsky** [comment]
@Alspaladin This isn't a bug, node <`v4`  has officially reached EOL , time to upgrade :D. But release should have been a SemVer Major though

**Comment by k0nserv** [comment]
Should be restricted with `engines` even if node has officially been EOLd

**Comment by d3viant0ne** [comment]
Webpack dropped support for `0.10.x / 0.12.x` when NodeJS officially dropped their support of these versions. 

`Webpack will continue to drop support for versions as NodeJS does`

As far as the engines, see https://github.com/webpack-contrib/organization/issues/7
