### ISSUE TITLE
Potential crash in removeStyleElement when sourcemaps are enabled

### ISSUE THREAD

**Issue by Kovensky** [webpack-contrib/style-loader#179]
**Do you want to request a *feature* or report a *bug*?**
Bug report

**What is the current behavior?**

`TypeError: cannot read property 'removeChild' of null` in the line `styleElement.parentNode.removeChild(styleElement);`. The `styleElement` exists, but its blob URL is not registered, and the `parentNode` is `null`.

Looking a few stack traces up, in the `addStylesToDom` call, the bad function call is the line `domStyle.parts[j](item.parts[j]);`. However, while `domStyle.parts.length === 2`, `item.parts.length === 1`; this seems to lead to the `<link>` element being created when `j` is `0`, and immediately destroyed when `j` is `1` before it gets passed to the `addStyle` call that would attach to the DOM.

**If the current behavior is a bug, please provide the steps to reproduce.**

I am not entirely sure on the steps needed yet, but it might be related the file being processed (`item.id`) being empty after going through loaders (nothing but stylus variable declarations). Alternatively, it is not going through loaders correctly due to `css-loader`'s `importLoaders` hack.

**What is the expected behavior?**

No crash.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

`webpack@2.2.1`, `style-loader@0.13.2`, `node@7.6.0`.

**Comment by PanJ** [comment]
Happened to me and then I tracked down and found this issue. Being recently discovered, could this be a bad combination of webpack & webpack loader versions? Tried to downgrade but still no luck.

**Comment by michael-ciniawsky** [comment]
@Kovensky 👋 Do maybe have a fix in mind ? 😛 See also #182

**Comment by Kovensky** [comment]
Nope, I still have no idea how this happens 😆

I just tried to debug the current state as of the crash, but I don't know what leads to the bad state. I ended up making a hack loader to delete the specific `@import` that pointed to the (ultimately) empty file before css-loader saw it 😕

**Comment by michael-ciniawsky** [comment]
Could you link me to the code? But I have the slight feeling it will be complicated 🤣

**Comment by evilebottnawi** [comment]
@Kovensky can you create minimal test repo, it is speed up the solution of the problem :smile:

**Comment by michael-ciniawsky** [comment]
If this is still relevant reopen anytime with a reproducible test repo (as simple as possible) :D
