### ISSUE TITLE
CSS modules and composes colliding with style-loader?

### ISSUE THREAD

**Issue by brandondurham** [webpack-contrib/style-loader#182]
**Do you want to request a *feature* or report a *bug*?**
Possible bug.

**What is the current behavior?**
When using CSS Modules with `composes` alongside `style-loader` I get the following error in the browser console:

```
Dynamic page loading failed TypeError: Cannot read property 'removeChild' of null
    at removeStyleElement (eval at ./node_modules/style-loader/addStyles.js (main.js:9851), <anonymous>:123:25)
    at remove (eval at ./node_modules/style-loader/addStyles.js (main.js:9851), <anonymous>:169:4)
    at Array.updateStyle (eval at ./node_modules/style-loader/addStyles.js (main.js:9851), <anonymous>:181:4)
    at addStylesToDom (eval at ./node_modules/style-loader/addStyles.js (main.js:9851), <anonymous>:69:22)
    at module.exports (eval at ./node_modules/style-loader/addStyles.js (main.js:9851), <anonymous>:37:2)
    at eval (eval at ./app/containers/Packages/styles.css (4.chunk.js:69), <anonymous>:7:77)
    at Object../app/containers/Packages/styles.css (4.chunk.js:69)
    at __webpack_require__ (main.js:687)
    at fn (main.js:106)
    at Object.eval (eval at ./app/containers/Packages/index.js (4.chunk.js:62), <anonymous>:13:70)
```

If I remove the `composes` from the relevant css files the page loads without errors.

**If the current behavior is a bug, please provide the steps to reproduce.**
I haven’t tried this with a clean repo, but it happens when I use this loader setup:

```
test: /\.css/,
exclude: /node_modules/,
use: [
	'style-loader',
	{
		loader: 'css-loader',
		options: {
			modules: true,
			localIdentName: '[folder]__[local]___[hash:base64:5]',
			importLoaders: 2
		}
	},
	'postcss-loader'
]
```

IWth that, any `composes` property that loads a style from an external file will cause the error. Something like this:

`composes: default from "styles/contentBlocks.css";`

FWIW, If I add this check to `removeStyleElement()` in `addStyles.js` everything works:

```
function removeStyleElement(styleElement) {
	if (styleElement.parentNode === null) return false; // This line
	styleElement.parentNode.removeChild(styleElement);
	var idx = styleElementsInsertedAtTop.indexOf(styleElement);
	if(idx >= 0) {
		styleElementsInsertedAtTop.splice(idx, 1);
	}
}
```

**What is the expected behavior?**
For `composes` to work without causing issues for `style-loader`.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
- MacOS Sierra v10.12.3
- webpack v2.2.1
- style-loader v0.13.2
- css-loader v0.26.2
- postcss-loader v1.3.3
- Node v6.9.4

**Comment by brandondurham** [comment]
Possibly related to #179 ?

**Comment by michael-ciniawsky** [comment]
@brandondurham Mind to send that check as a PR 😛 ?

**Comment by diegohaz** [comment]
I'm also having this problem and `if (styleElement.parentNode === null) return false;` solved it (at least, it didn't crash).

**Comment by lunikon** [comment]
I'm pretty sure I'm seeing this exact issue. Except that I'm using less-loader instead of postcss-loader.

**Comment by MrOrz** [comment]
Encountered this with `webpack.NamedModulesPlugin`. Removing `new webpack.NamedModulesPlugin(),` from `plugins` works for me.

Reference: http://stackoverflow.com/a/43080181

**Comment by michael-ciniawsky** [comment]
Did someone here investigate further on this ? The fix looks sane, but would need to be tested, if it may break other usecases. PR welcome && appreciated
