### ISSUE TITLE
Recommended configuration misleading

### ISSUE THREAD

**Issue by jAndreas** [webpack-contrib/style-loader#184]
**Do you want to request a *feature* or report a *bug*?**

report a bug

**What is the current behavior?**

Wrong documentation or wrong code. The "useable" feature from the style-loader won't get called if you set it up with the recommended configuration. The style-loader doesn't understand the "options" object, so creating an option field with the property "useable: true" doesn't affect anything. You have to pass the loader string as "style-loader/useable" in order to make it work, which is contrary to https://webpack.js.org/loaders/style-loader/#recommended-configuration

**Comment by ekulabuhov** [comment]
Agree. `useable` is not an option, it's a path. Could you submit a PR?

**Comment by michael-ciniawsky** [comment]
fixed by #185
