### ISSUE TITLE
Need to have Reference-counted API and Local scope CSS at the same time

### ISSUE THREAD

**Issue by budarin** [webpack-contrib/style-loader#187]
Why if I use Reference-counted API I have no access to local scope class names?
Does it mean that this modes nave not to be used at the same time

**Comment by michael-ciniawsky** [comment]
@budarin Please give an example why/what/how you mean that and in regrad of the usecase 😛

**Comment by budarin** [comment]
I need to setup classes in a component & through hoc "Styled" in WillMount & WillUnmount handlers set/remove styles in document

**Comment by michael-ciniawsky** [comment]
and `style.use()/style.unused()` wouldn't work for you ?

**Comment by budarin** [comment]
they work fine but I have not hash with classNames (

**Comment by michael-ciniawsky** [comment]
Please also post a component and pseudo code of the desired CSS usage (doesn't matter how it looks like) to clarify futher

cc @bebraw @d3viant0ne @ekulabuhov

**Comment by budarin** [comment]
HOC Styled
```
import React from 'react';

const styled = styles => TargetComponent => {
    const componentWillMountOriginal = TargetComponent.prototype.componentWillMount;
    const componentWillUnmountOriginal = TargetComponent.prototype.componentWillUnmount;

    // We need a counter because with Fiber cWM may be called multiple times
    TargetComponent.prototype.count = 0;

    TargetComponent.prototype.componentWillMount = function componentWillMount() {
        this.count += 1;
        if (this.count === 1) {
            styles.use();
        }
        if (componentWillMountOriginal) {
            componentWillMountOriginal.call(this);
        }
    };

    TargetComponent.prototype.componentWillUnmount = function componentWillUnmount() {
        styles.unuse();
        this.count = 0;
        if (componentWillUnmountOriginal) {
            componentWillUnmountOriginal.call(this);
        }
    };

    return function StyledComponent(props) {
        return <TargetComponent {...props} classes={styles} />;
    };
};

export default styled;
```

Component
```
import React from 'react';
import styled from '../utils/hocs/styled';
import styles from './App.css';

@styled(styles)
class App extends React.Component {
    static propTypes = {
        classes: React.PropTypes.object.isRequired,
    };

    render() {
        const { classes } = this.props;

        return (
            <div>
                <div style={{ color: 'green' }} className={classes.big}>Hello the World !</div>
            </div>
        );
    }
}

export default App;
```

App.css
```
.big {
    font-size: 24px;
}
```

**Comment by ekulabuhov** [comment]
@budarin Useable moves locals into a separate object: 

var css = require('./localScoped.css');
css.locals.className === 'localScoped-className_3dIU6Uf';

Hope that helps!

**Comment by budarin** [comment]
```
import css from './App.css';
```
I see only ref/unref & use/unuse properties in css.
There is no locals in css object

**Comment by ekulabuhov** [comment]
Are you up to date? Could you post your loader versions?

**Comment by budarin** [comment]
style-loader 0.13.2
css-loader 0.27.3

**Comment by ekulabuhov** [comment]
Hmm, according to [style-loader docs](https://github.com/webpack-contrib/css-loader#css-scope) you need to wrap your css styles inside :local, e.g.:

:local(.big) {
  font-size: 24px;
}

**Comment by budarin** [comment]
accordin to [css-loader doc](github.com/webpack-contrib/css-loader)
```
{
      loader: 'css-loader',
      options: {
        modules: true,
        localIdentName: '[path][name]__[local]--[hash:base64:5]'
      }
    }
```
setting modules: true - The loader replaces local selectors with unique identifiers. The choosen unique identifiers are exported by the module.

**Comment by michael-ciniawsky** [comment]
@budarin Please make a small test repo for reproduction and debugging

**Comment by ekulabuhov** [comment]
Sorry, I can't recreate your problem. Could you try deleting your node_modules folder and installing everything again? Or if you could create a minimal repo that has your problem I could take a look.

**Comment by budarin** [comment]
Ok, I'l try to create minimal project to reproduce tthe problem tomorrow or later 23:43, 13 марта 2017 г., Eugene Kulabuhov <notifications@github.com>:Sorry, I can't recreate your problem. Could you try deleting your node_modules folder and installing everything again? Or if you could create a minimal repo that has your problem I could take a look.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.    С уважением Бударин Вадим

**Comment by budarin** [comment]
Please try to install [https://github.com/budarin/simple-style-css-loader](https://github.com/budarin/simple-style-css-loader) and try run it
by default options are for use css module - imports hash object with hashed classnames

try then modify webpack.config.js 'style-loader' to 'style-loader/useable' and change in components classname acessors from styles.<classname> to styles.locals.<classname>

**Comment by ekulabuhov** [comment]
Hi! It appears that your issue is fixed but not published yet: https://github.com/webpack-contrib/style-loader/pull/128

You can try it out by npm installing from the repo directly. Or just wait a bit.

**Comment by d3viant0ne** [comment]
I'll get it out shortly

**Comment by michael-ciniawsky** [comment]
Of course..., I even merge that one 🤣 @ekulabuhov Thx

```
{
  "devDependencies": {
     "style-loader": "webpack-contrib/style-loader"
  }
}
```
@budarin Please test and if there are still any regressions feel free to reopen :)

@d3viant0ne 👍

**Comment by d3viant0ne** [comment]
`0.14.0` is out on npm. 

Changelog can be found here - https://github.com/webpack-contrib/style-loader/blob/master/CHANGELOG.md

**Comment by budarin** [comment]
Thanks!
It works.
