### ISSUE TITLE
please turn convertToAbsoluteUrls explicitly off.

### ISSUE THREAD

**Issue by karolyi** [webpack-contrib/style-loader#195]
Hey,

I just spent half a day with investigating why my webpack live server (with `style-loader`) was corrupting the converted bootstrap CSS source.

turns out the culprit is `convertToAbsoluteUrls`. it entered 9 days ago (https://github.com/webpack-contrib/style-loader/blame/master/addStyles.js#L261-L266) into the codebase.

Unless you don't intentionally want to cause headache for other devs like me, please turn it explicitly off. I had to add its option to my config to fix the SASS rendering with sourcemap, while I almost submitted an issue to the bootstrap guys.

**Comment by karolyi** [comment]
some more information: this setting adds urls to blob: attributes. that's definitely a bug.

**Comment by michael-ciniawsky** [comment]
@karolyi Config and a small example please

**Comment by michael-ciniawsky** [comment]
> If convertToAbsoluteUrls isn't defined, but sourcemaps are enabled and there is no publicPath defined then lets turn convertToAbsoluteUrls on by default.  Otherwise default to the convertToAbsoluteUrls option directly

Just to confirm, this isn't an option for you ?

**Comment by michael-ciniawsky** [comment]
Eventual docs update needed

**Comment by karolyi** [comment]
Right now I don't have an easy example, but here's a bug that convertToAbsoluteUrls was causing.

After transpiling bootstrap.scss into CSS, [this line](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L270) that uses [this variable](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L590) is corrupted as the variable adds the current url to the `url("data:image/svg+xml;charset=utf8 ...` attribute.

So in my case, it became:
`url("http://localhost:8000/account/login/data:image/svg+xml;charset=utf8 ...`

which is obviously bad.

There were more errors which I didn't investigate further, but this was the most eye catching. After turning the option off, the CSS got generated in the right way.

**Comment by michael-ciniawsky** [comment]
@sontek Sry for pinging you again on this, but would you be so kind and take a look again providing me some guidance what to do about it 😛 e.g could it be disabled by default or would it break builds the other way around then again 🙃 ?

**Comment by sontek** [comment]
@karolyi What version of `style-loader` were you using?  This sounds like the issue we fixed in the last PR

**Comment by sontek** [comment]
Oh, looks like no one released that fix.  I'm sorry about that @karolyi this is actually fixed (and has been fixed for 4 days), it just hasn't been released to `npm` yet.

@michael-ciniawsky Any chance you can push a release with the fix?

**Comment by michael-ciniawsky** [comment]
@sontek Thx

cc @d3viant0ne @bebraw

**Comment by sontek** [comment]
Should we keep this opened until we release and he verifies?

**Comment by d3viant0ne** [comment]
It's already been released

**Comment by karolyi** [comment]
I'll test it soon and give you guys a feedback. bear with me :)

**Comment by karolyi** [comment]
can confirm it seems to have fixed in `0.15.0`. yesterday I was using `0.14.1`.

cheers guys

**Comment by sontek** [comment]
*phew* I was going to be very confused if that PR didn't fix it :D

**Comment by mgol** [comment]
This still doesn't work in some cases. I reported #214.
