### ISSUE TITLE
window -> self change causes errors with other projects

### ISSUE THREAD

**Issue by tsnieman** [webpack-contrib/style-loader#199]
Hello - I just wanted to bring attention to this comment: https://github.com/webpack-contrib/style-loader/commit/9dc45a6dee16553a64071031d18feb1562df86a2#commitcomment-21377913

Which notes that this change - 9dc45a6dee16553a64071031d18feb1562df86a2 - broke isomorphic-webpack. (see gajus/isomorphic-webpack#20)

Thoughts on using `window.self` instead of `self`?

**Comment by michael-ciniawsky** [comment]
@tsnieman https://github.com/webpack-contrib/style-loader/blob/master/addStyles.js#L19 Could someone using `isomorphic-webpack` try against latest `style-loader@latest` ? 🙃 

⚠️  It's definitely agreed upon **not** supporting any SSR-ish functionality within `style-loader`, only browser + third parties mimicking the DOM (e.g JSDOM) (not 💯 sure if this applies here)

**Comment by mgol** [comment]
In the Node.js + jsdom scenario all browser globals are available under `window` but not necessarily under the global; hence the need to take all browser globals from `window`.

**Comment by michael-ciniawsky** [comment]
This should be fixed now, reopen if still  any regressions
