### ISSUE TITLE
split addStyle into parts

### ISSUE THREAD

**Issue by sokra** [webpack-contrib/style-loader#201]
**Do you want to request a *feature* or report a *bug*?**
refactoring

**What is the current behavior?**
`addStyle` include all runtime code. Depending on provided options only a part of the code is used.

Debug only feature (i. e. sourceMaps) are included in the production bundle.

**What is the expected behavior?**
Only the needed code is loaded. The loader decides on compile-time which runtime code is needed and injects only these parts.

For this `addStyle.js` need to be splitted into parts.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Reduce the bundle size.

**Comment by kevinkace** [comment]
Is this still being worked on?

**Comment by evilebottnawi** [comment]
Also we should generate hmr code inside `inject*` code only when hmr enabled

**Comment by alexander-akait** [comment]
Done
