### ISSUE TITLE
release v1

### ISSUE THREAD

**Issue by graingert** [webpack-contrib/style-loader#202]
It seems a lot of changes recently from 0.x to 0.x+1 have had no breaking changes reported in the changelog: release v1 and stick to semver re: breaking changes, so I can use the ^1.0.0 semver range

**Comment by michael-ciniawsky** [comment]
@graingert In progress 😛 , but we are changing internals `webpack-defaults` beforehand and refactor the code keeping the current features, while the API (`options`) may change for better usage in `v1.0.0` alongside with other refactorings #201, that eventually may or may not be `breaking chnages` for someone. Starting form `v1.0.0` `style-loader` and other webpack-contrib projects will keep strict semver using `standard-version`. So please be patient :D
