### ISSUE TITLE
No-Op in a worker

### ISSUE THREAD

**Issue by jasonLaster** [webpack-contrib/style-loader#203]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Currently, `addStyles` errors when running in a worker context.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. add `require("styles.css")` to `foo.js`
2. `new Worker("foo.js")`

**What is the expected behavior?**

`addStyles` is a no-op in the worker context and does not try to add the stylesheet.

**Comment by michael-ciniawsky** [comment]
@jasonLaster See #201 for the general plan regarding `addStyles`, maybe this could go hand in hand, tbh I'm not really familiar with Web Worker's atm, any help or PR even for discussion/testing is highly welcome :)

**Comment by michael-ciniawsky** [comment]
Closing according to #201
