### ISSUE TITLE
Can't resolve './fixUrls' in '/Users/nikos/WebstormProjects/Density-Wars/node_modules/style-loader'

### ISSUE THREAD

**Issue by QuantumInformation** [webpack-contrib/style-loader#206]
I have this config here

https://github.com/QuantumInformation/Density-Wars/blob/master/webpack.config.js#L36

When I try run `webpack` I get the following error:

![image](https://cloud.githubusercontent.com/assets/216566/24578110/97419232-16d1-11e7-8f0f-476f8d293517.png)

**Comment by willhalling** [comment]
+1 same issue.

**Comment by QuantumInformation** [comment]
For some reason this error has disappeared for me, closing.

**Comment by jeff-kilbride** [comment]
I just upgraded from 0.13.2 to 0.16.1 and I'm getting this same error.

@QuantumInformation  any idea how it was fixed for you?

**Comment by QuantumInformation** [comment]
Sorry can't say, did you look at my config?

**Comment by jeff-kilbride** [comment]
You're config looks pretty straightforward. Mine is here:

https://gist.github.com/jeff-kilbride/e58a6831546efeb43fef8fae6b2d1da6

This is the line that's causing a problem, or at least giving the error:
```
	fixUrls = require("./fixUrls");
```
However, the file `fixUrls.js` does exist in my `style-loader` directory. So, I'm confused as to why it can't resolve the file.

**Comment by QuantumInformation** [comment]
Sorry mate, I just do enough webpack to get by and don't dig too deep!
Btw are you from Scotland?

**Comment by jeff-kilbride** [comment]
@QuantumInformation  I'm from Los Angeles. My paternal grandfather was born in Ireland, though -- hence the gaelic name. However, I have a very large group of ex-pat Irish / Scottish friends.   😃 

I've dug a little deeper into this issue in #211, if you're interested in following it.

**Comment by QuantumInformation** [comment]
Cool thanks, I'm from  town called East kilbride
