### ISSUE TITLE
InsertInto option doesn't work when a selector to a shadow element is specified.

### ISSUE THREAD

**Issue by pastelsky** [webpack-contrib/style-loader#207]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Style loader fails to find the DOM element to insert the styles into, when a css selector having a shadow root is used like `#host::shadow>#root` as specified in the example.

This is probably happening because `style-loader` internally uses `document.querySelector` to get the DOM element to insert to, however, Shadow DOM elements cannot be accessed this way.

```js
document.querySelector('#host::shadow')
// null
document.querySelector('#host').shadowRoot()
// [Element]
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a shadow root - 
```js
let e = document.createElement('div');
let shadowRoot = e.createShadowRoot();
```

Then use style loader with `insertAt:div::shadow`

**What is the expected behavior?**
Expected: Inserts it into the div
Actual: Show an error in the console - element not found

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
Webpack 2.1
Latest style loader

**Comment by jrbotros** [comment]
Looks like shadow-piercing selectors are [all deprecated](https://www.chromestatus.com/features/6750456638341120). Trying to figure this out myself, will let you know if I have any luck!

**Comment by jrbotros** [comment]
@pastelsky As a workaround, I used the [`attrs` option](https://github.com/webpack-contrib/style-loader/blob/master/README.md#attrs) to set a class name on each style tag, then injected them manually:
```
document.querySelectorAll('.webpack-styles').forEach((style) => {
  shadowEl.appendChild(style);
});
```

**Comment by michael-ciniawsky** [comment]
Someone here interested in spinning up a PR for this 🙃 ?

**Comment by jimsimon** [comment]
It looks like a duplicate issue was opened (#256) and someone has a proposed fix posted in there.

**Comment by evilebottnawi** [comment]
Closed in favor https://github.com/webpack-contrib/style-loader/issues/256
