### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/style-loader#209]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

The package contains files that are unnecessary for work (.github template, tests and etc)
For see all files run `npm pack` and open archive.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

Reduce `node_modules` disk size.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

No matter.

I can do PR if your accept this.

**Comment by michael-ciniawsky** [comment]
😆 👋  Yep PR welcome, preferable via `pkg.files`

**Comment by michael-ciniawsky** [comment]
Closed by #210
