### ISSUE TITLE
insertInto for iframes

### ISSUE THREAD

**Issue by SeeThruHead** [webpack-contrib/style-loader#213]
Feature

insertInto is limited to a string which is passed to document.querySelector

It would be nice if iframe support was included into insertInto as we often want to load css into an iframe for embedded widgets and the like.

**Comment by tobias-zucali** [comment]
+1, we are also searching for that feature!

**Comment by evilebottnawi** [comment]
@tobias-zucali PR welcome :+1:

**Comment by amirbilu** [comment]
+1 would love to see this feature integrated!
