### ISSUE TITLE
IE11 syntax error in addStyles.js

### ISSUE THREAD

**Issue by amie-wilt** [webpack-contrib/style-loader#220]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

IE11 is throwing a Syntax error in addStyles.js.

**If the current behavior is a bug, please provide the steps to reproduce.**

My config:

https://gist.github.com/amie-wilt/643773311eadf621db5a46454b768efb

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

Mac Sierra (10.12.4)
Node: 7.8.0
Webpack: 2.3.3

**Comment by michael-ciniawsky** [comment]
@amie-wilt Please also post the Syntax Error here :)

**Comment by amie-wilt** [comment]
@michael-ciniawsky Sorry about that!

<img width="291" alt="screen shot 2017-04-24 at 4 10 29 pm" src="https://cloud.githubusercontent.com/assets/8226176/25356578/ab15a9c6-2908-11e7-9fbf-87c464a19239.png">

<img width="750" alt="screen shot 2017-04-24 at 4 10 41 pm" src="https://cloud.githubusercontent.com/assets/8226176/25356580/ac6bdde0-2908-11e7-926b-4286b651cfb6.png">

**Comment by evilebottnawi** [comment]
@amie-wilt can your disable all required extra `required`, some polyfill or other library can change default browser behavior, or your can create test minimal reproduce repo, it is allow asap fix bug :+1:

**Comment by amie-wilt** [comment]
@evilebottnawi sorry it's taken awhile for me to get back. This issue is not related to this loader but rather I did not have babel-polyfill for async/await in my webpack config. Sorry for the unnecessary issue.
