### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sourceMap' of undefined

### ISSUE THREAD

**Issue by dsempel** [webpack-contrib/style-loader#234]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After upgrading to v0.18.0 and trying to run my application with webpack-dev-server it produces the following error and I get a blank page.
```
Uncaught TypeError: Cannot read property 'sourceMap' of undefined
    at addStyle (eval at ./node_modules/style-loader/lib/addStyles.js (main.js:6068), <anonymous>:237:6)
    at addStylesToDom (eval at ./node_modules/style-loader/lib/addStyles.js (main.js:6068), <anonymous>:107:25)
    at module.exports (eval at ./node_modules/style-loader/lib/addStyles.js (main.js:6068), <anonymous>:67:2)
    at eval (eval at ./src/containers/pages/About/About.scss (main.js:6812), <anonymous>:12:81)
    at Object../src/containers/pages/About/About.scss (main.js:6812)
    at __webpack_require__ (manifest.js:692)
    at fn (manifest.js:115)
    at eval (eval at ./src/containers/pages/About/About.js (main.js:6805), <anonymous>:17:14)
    at Object../src/containers/pages/About/About.js (main.js:6805)
    at __webpack_require__ (manifest.js:692)
```

I looked at `addStyles.js`, but could not figure out why `obj` would be undefined.
This is the relevant part of my webpack config (all loaders are at latest version):
```
{
	test: /\.scss$/,
		use: ExtractTextPlugin.extract(
	{
		fallback: 'style-loader',
		use: [
			{
				loader: 'css-loader',
				options: {
					modules: true,
					importLoaders: 3,
					localIdentName: production ? '[hash:6]' : '[local]-[hash:5]',
					sourceMap: true
				}
			},
			{ loader: 'postcss-loader', options: { sourceMap: true } },
			{ loader: 'resolve-url-loader', options: { keepQuery: true } },
			{ loader: 'sass-loader', options: { outputStyle: 'expanded', sourceMap: true } }
		]
	})
}
```

**Other relevant information**
webpack: 2.5.1
node: v7.9.0
MacOS Sierra

**Comment by michael-ciniawsky** [comment]
`config.devtool` please && does this also happen without `extract-text-webpack-plugin`? This latter is especially odd, because should be use only if something went wrong during extraction

**Comment by michael-ciniawsky** [comment]
@dsempel  Could you try this out please (#236)  `npm i -D webpack-contrib/style-loader#fix`

**Comment by dsempel** [comment]
Your fix seems to be working fine! Thank you.
Don't know if you still need it:
`config.devtool: production ? 'source-map' : 'cheap-module-eval-source-map'`
`extract-text-webpack-plugin` is actually disabled for development.

**Comment by evilebottnawi** [comment]
@dsempel can your provide minimal test repo where error occurred? We need to understand
 why it is happens and add tests (no regression in future).

**Comment by dsempel** [comment]
Ok I will try to provide something tomorrow. It's a big repo with quite a complex webpack setup, but I'll try!

**Comment by evilebottnawi** [comment]
@dsempel It will be great :+1:

**Comment by michael-ciniawsky** [comment]
@dsempel Thx, yeah that was the only logic related change between `0.17.0...0.18.0` and yeah...😅

**Comment by dsempel** [comment]
I'm sorry, I tried but could not get a test repo to fail with the same error.. I'm pretty sure it has nothing to do with ExtractTextPlugin. It's probably a combination of `webpack-dev-server` and something else.. 
In the repo where the error does occur, I run this: `webpack-dev-server --hot --inline --config ./webpack.config.js`. The css setup includes: Sass, PostCSS and css modules.

**Comment by eyaylagul** [comment]
this work for me
```javascript
const config = require('../config/index');
```
