### ISSUE TITLE
HMR webpack-dev-server not working with style-loader 0.18.0

### ISSUE THREAD

**Issue by johnfake** [webpack-contrib/style-loader#237]
HotModuleReplacement works fine with style-loader 0.17.0 and Webpack 2 but not with 0.18.0.

**What is the current behavior?**
With the latest version any change in the css files results in a complete page-reloader instead of a HotModuleReplacement ;). 

**What is the expected behavior?**
changes in css/scss files should not force the browser to reload the entire page

Regards
Alex

**Comment by evilebottnawi** [comment]
@johnfake maybe fixed in https://github.com/webpack-contrib/style-loader/pull/236, can your try to use `master` branch, if it still don't work please create minimal reproducible test repo. Thanks!

**Comment by johnfake** [comment]
@evilebottnawi works fine with master branch! Any plans for releasing a new package on npm? Thanks!

**Comment by evilebottnawi** [comment]
@johnfake yep, in the soonest time

**Comment by johnfake** [comment]
for a workaround we can use napa and clone this repo into our package.json

**Comment by evilebottnawi** [comment]
@johnfake or use `style-loader` `0.17.0`, if your don't have problems with old version. Seems no critical changed between `0.17.0` and `0.18.0`.
