### ISSUE TITLE
package namespace update

### ISSUE THREAD

**Issue by zhenyulin** [webpack-contrib/style-loader#239]
Is there any cons to update the package name to webpack-style-loader so that the loader packages namespace can be unified as like for babel?

**Comment by michael-ciniawsky** [comment]
We could consider to publish them under an organisation namespace `@webpack/style-loader @webpack-contrib/style-loader`, but this needs triag an consensus amongst webpack/webpack-contrib. Feel free to open an RFC in webpack-contrib/organisation as recommendation, but for a single repo not atm sry, the 'inofficial' convention is `${name}-loader` / `${name}-webpack-plugin` which is not the best for sure :D
