### ISSUE TITLE
style-loader breaks webpack(1) HMR ?

### ISSUE THREAD

**Issue by BerndWessels** [webpack-contrib/style-loader#246]
Updating sass variables will only work once - after that HMR refused to work - most likely related to `style-loader`.

Please find bug description and details [here](https://github.com/storybooks/storybook/issues/1155)

**Comment by evilebottnawi** [comment]
@BerndWessels seems you found solution https://github.com/storybooks/storybook/issues/1155#issuecomment-305346087, can we close issue here?

**Comment by michael-ciniawsky** [comment]
Feel free to reopen if still regressions :)
