### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by imnot2** [webpack-contrib/style-loader#249]
style-loader@0.18.1

my webpack config
```javascript
{
        test: /\.less$/,
        loader: CSSExtractor.extract({ use: ['style-loader', 'css-loader', 'postcss-loader', 'less-loader'] }),
}
```
![image](https://user-images.githubusercontent.com/4587852/27364113-1792812a-566b-11e7-9471-19dc08d9dbdf.png)

**Comment by michael-ciniawsky** [comment]
`style-loader` adds code to your webpack bundle to **load** the CSS via `<style></style>` tags, most of the time during development

```diff
-  loader: CSSExtractor.extract({ use: ['style-loader', 'css-loader', 'postcss-loader', 'less-loader'] })
+ loader: CSSExtractor.extract({ 
+  fallback: 'style-loader',
+  use: ['css-loader', 'postcss-loader', 'less-loader'] 
+ })
```

`window` isn't defined, because there isn't any during CSS extraction  :)
