### ISSUE TITLE
Can't get /url to work

### ISSUE THREAD

**Issue by MatTheCat** [webpack-contrib/style-loader#252]
```javascript
{
    test: /\.css$/,
    use: [
        "style-loader/url",
        "file-loader",
        {
            loader: "css-loader",
            options: { importLoaders: 1 }
        },
        "postcss-loader"
    ]
}
```

Above configuration does indeed inject `<link>` tags into the DOM but their content is like

```javascript
exports = module.exports = require("../../../../../../node_modules/css-loader/lib/css-base.js")(undefined);
// imports


// module
exports.push([module.id, "CSS content", ""]);

// exports
```

What am I doing wrong?

**Comment by michael-ciniawsky** [comment]
This is because of `css-loader`, which has a 'special' format for CSS `[[id, css, map, ...]]`, could you try without `css-loader` ?

**Comment by MatTheCat** [comment]
It's working without `css-loader` but I need it to resolve  `url()`. Is there a way to use both `style-loader/url` and `css-loader`?

**Comment by michael-ciniawsky** [comment]
Maybe `to-string-loader` between style-loader && `css-loader` the `css-loader` format is an `{Array}` which is untangled,when calling `arr.toString()` on it  ⚠️ Note that this will **not** dedupe any CSS then, which is the reason for the `{Array}` format in the first place :)

**Comment by MatTheCat** [comment]
I tried

---

1. style-loader/url
2. to-string-loader
3. file-loader
4. css-loader

⤷ Same issue.

---

1. style-loader/url
2. to-string-loader
3. css-loader

⤷ CSS content is dumped in `<link>` `href`.

---

1. style-loader/url
2. file-loader
3. to-string-loader
4. css-loader

⤷ CSS file contains

```javascript
var result = require("!!../../../../../../node_modules/css-loader/index.js?{\"importLoaders\":1}!../../../../../../node_modules/postcss-loader/lib/index.js!./style.css");

        if (typeof result === "string") {
            module.exports = result;
        } else {
            module.exports = result.toString();
        }
```

---

Seems there is no way to achieve this :disappointed:

**Comment by ivan7237d** [comment]
Me too I'm stuck with this  🤔 I'm new to webpack and so I have a hunch I'm missing something obvious.

What I'm trying to do shouldn't be that rare of a use case — I want be able to tweak styles in Chrome, and have changes automatically saved to disk with Workspace feature. For that to happen, css files shouldn't undergo any transformations in dev mode (so it looks like I need `style-loader/url` + `file-loader`), but I do also need the `css-loader` in order to resolve images and fonts.

But so far it sounds like I should create a custom loader to put in between `file-loader` and `css-loader`... I'll either try that or will process images and fonts outside of webpack.

**Comment by michael-ciniawsky** [comment]
[extract-loader](https://github.com/peerigon/extract-loader) && `extract-text-webpack-plugin` I checked various options and it doesn't work to use the `css-loader` in conjunction with `style-loader/url`, the `url` option is mainly meant to support static assets insertions [in dev mode], if your project requires this to work correctly, but a simple `<link href="cdn/path/to/lib.css rel="stylesheet">` in `index.html` maybe works even better for that purpose :). Not every assets needs to go 'through' webpack 'forcefully'. If it the file needs to resolve `url()` etc, this doesn't apply of course and as stated `extract-loader` || `extract-text-webpack-plugin` are needed then

**Comment by ivan7237d** [comment]
@michael-ciniawsky Thanks vm for the tip! `extract-loader` indeed does the trick. 

But I ended up using `style-loader` + `file-loader` in dev mode, and just copy all images with CopyWebpackPlugin. The Chrome's Workspace feature is amazing for editing styles, and I have it working now.
