### ISSUE TITLE
Can't resolve './urls'

### ISSUE THREAD

**Issue by Bkucera** [webpack-contrib/style-loader#254]
Style-loader: ^0.18.2  
Configuration: node v6.11.0 , npm  v3.10.10

```
{
            test: /\.css$/,
            exclude: /node_modules/,
            use: ['style-loader', 'css-loader']
 }
```

gives this error on webpack build
```
ERROR in ./~/style-loader/lib/addStyles.js
Module not found: Error: Can't resolve './urls' in 'C:\...\project_directory\node_modules\style-loader\lib'
 @ ./~/style-loader/lib/addStyles.js 44:14-31
```
Module works correctly if I change `addStyles.js:44` from `require('./urls')` to `require('./urls.js')`

**Comment by evilebottnawi** [comment]
@Bkucera can your provide minimum reproducible test repo? Also give information about nodejs version?

**Comment by danhdoancs** [comment]
I got the same error and it took me a good hour to realize that the resolve values of webpack.config.js are not correctly set. They missed "." before the extensions.
    resolve: {
        extensions: ['.js','.jsx']
    }

**Comment by evilebottnawi** [comment]
@danhdoancs can your provide minimum reproducible test repo?

**Comment by Bkucera** [comment]
@danhdoancs Thank you! This was my issue. its a shame webpack doesn't recognize the lack of dot, and show you a warning of some sort.

**Comment by Ross-Esmond** [comment]
It happened to me as well. My webpack config had the periods but I didn't have the '.js' extension in there. I just had '.ts' and '.tsx'. When I realized what I did it seemed kind of obvious. Just leaving a comment in case anyone else follows the exact same path I did.

**Comment by vadimkuragkovskiy** [comment]
so, I'll try to save a lot of time to someone :) 
In case with the error which was described above, here is the solution:

bad/error:
```javascript
resolve: {
        alias: {},
        modules: [],
        extensions: ['.css', '.less']
    },
```

good/no error:
```javascript
resolve: {
        alias: {},
        modules: [],
        extensions: ['.js', '.css', '.less']
    },
```

I hope it helps someone :)

**Comment by rosenbergdev** [comment]
Thanks! Don't forget to remove happypack cache if you're using it.

**Comment by searene** [comment]
I solved it by adding `.js` in `extensions`, but could anyone tell me why I need it when I'm only using typescript and css?

**Comment by navotgil** [comment]
WHY WHY OMG WHY!!!
I spent so much time on that one...
I guess there should be some kind of resolved extensions dependency mechanism

**Comment by slavafomin** [comment]
Hey there! I've got the same issue today. Could someone please explain why `.js` extension must be used in the `resolve.extensions` configuration option? Is it because the loader adds some JavaScript code to the generated bundle?

I also think the notice should be added to the README.
