### ISSUE TITLE
insertAt option doesn't work with style-loader/url

### ISSUE THREAD

**Issue by ingro** [webpack-contrib/style-loader#255]
**What is the current behavior?**
Setting `insertAt` has no effect when used with `style-loader/url`

**If the current behavior is a bug, please provide the steps to reproduce.**
```javascript
{
           test: /\.css$/,
                use: [
                    {
                        loader: 'style-loader/url',
                        options: {
                            insertAt: 'top'
                        }
                    },
                    { 
                        loader: "file-loader"
                    }
                ]
            }
```
The stylesheet generated by this rule gets appended at the bottome of the `head` tag instead to be on top (which works good using plain `style-loader` and `css-loader`)

**What is the expected behavior?**
The link to the generated stylesheet should be placed at the top of the `head` tag

**Comment by evilebottnawi** [comment]
@michael-ciniawsky seems we don't have `insertAt` and other option for `url`, we should fix schema for validate options.

**Comment by evilebottnawi** [comment]
Done in https://github.com/webpack-contrib/style-loader/pull/413, now you can use any custom logic for insert
