### ISSUE TITLE
HMR failed to update for CSS Modules when the file is empty

### ISSUE THREAD

**Issue by fedeoo** [webpack-contrib/style-loader#259]
**Do you want to request a *feature* or report a *bug*?**

Yes
**What is the current behavior?**
I have build a [demo](https://github.com/fedeoo/hmr-failed-case). In this project, the `src/Test.css` is empty. I add some styles to this file:
```css
.title { color: red; }
```
Nothing was happened! I found the style was updated correctly, but the page is not re-rendered.

**If the current behavior is a bug, please provide the steps to reproduce.**

You can start the demo and open the page in Chrome.  And then add styles to `src/Test.css`:
```css
.title { color: red; }
```
The page is not re-rendered. You can refresh the page in Chrome, and you will see the title is red.
If you change the `src/Test.css`, it will be re-rendered . But you clear the file `src/Test.css`,  you must refresh the page to see the changed page.

**What is the expected behavior?**
I want the page is re-rendered after I change `src/Test.css`
The similar issue is #148 

I think `content.locals` should be `{}` other than `undefined` If I enable css modules.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
webpack: 3.4.1
Node.js: v6.10.2
OS: MacOS Sierra 10.12.6

**Comment by evilebottnawi** [comment]
@fedeoo problem still exists? If yes can you provide minimum reproducible test repo?

**Comment by fedeoo** [comment]
The problem always exists. I have build a demo: https://github.com/fedeoo/hmr-failed-case

**Comment by Sanonz** [comment]
@fedeoo I met the same problem as you.

edit file: [https://github.com/webpack-contrib/style-loader/blob/master/useable.js#L35](https://github.com/webpack-contrib/style-loader/blob/master/useable.js#L35)
```js
data.refs = content.locals ? 0 : refs;
```
to
```js
data.refs = refs;
```
It works!

**Comment by evilebottnawi** [comment]
@Sanonz PR welcome

**Comment by evilebottnawi** [comment]
Confirm, let's fix it.

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack-contrib/css-loader

**Comment by evilebottnawi** [comment]
@michael-ciniawsky seems problem not in `style-loader`, this problem in `css-loader` inside `postcss-modules-scope`, but need investigate. I think we should move this issue from `style-loader`
