### ISSUE TITLE
style-loader/useable won't work on code splitting by webpack

### ISSUE THREAD

**Issue by Lenic** [webpack-contrib/style-loader#261]
我的 Webpack 配置是这样的：

My webpack's configuration is:

```js
import fs from 'fs';
import path from 'path';
import _ from 'underscore';
import webpack from 'webpack';
import HtmlWebpackPlugin from 'html-webpack-plugin';
import ExtractTextPlugin from 'extract-text-webpack-plugin';
import FriendlyErrorsPlugin from 'friendly-errors-webpack-plugin';

function resolve(dir) {
  return path.join(__dirname, dir);
}

export default {
  entry: {
    vendor: [
      'underscore',
      'es6-promise/auto',
      'axios',
      'vue',
      'vuex',
      'vue-router',
      resolve('../src/lib/utils'),
      resolve('../src/res/css'),
    ],
    app: resolve('../src/client'),
  },
  output: {
    filename: '[name].js',
    path: resolve('../dist'),
  },
  module: {
    rules: [
      {
        test: /\.(js|vue)$/,
        loader: 'eslint-loader',
        enforce: 'pre',
        include: [resolve('../src/client'), resolve('../src/lib')],
        options: {
          formatter: require('eslint-friendly-formatter')
        }
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: 'babel-loader',
      },
      {
        test: /\.vue$/,
        exclude: /node_modules/,
        use: 'vue-loader',
      },
      {
        test: /\.attached\.less$/,
        exclude: /\.global\.less$/,
        use: [
          { loader: 'style-loader/useable' },
          { loader: 'css-loader' },
          { loader: 'less-loader' },
        ],
      },
      {
        test: /\.global\.less$/,
        exclude: /\.attached\.less$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            { loader: 'css-loader' },
            { loader: 'less-loader' },
          ],
        }),
      },
      {
        test: /\.less$/,
        exclude: [/\.global\.less$/, /\.attached\.less$/],
        use: [
          { loader: 'style-loader' },
          { loader: 'css-loader' },
          { loader: 'less-loader' },
        ],
      }
    ],
  },
  resolve: {
    extensions: ['.js', '.vue', '.attached.less', '.global.less', '.less'],
    alias: {
      '$lib': resolve('../src/lib'),
    }
  },
  plugins: [
    new HtmlWebpackPlugin({
      title: 'Vuex Test',
      template: resolve('index.html'),
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: ['vendor', 'manifest'],
      minChunks: Infinity,
    }),
    new ExtractTextPlugin('[name].css'),
    new FriendlyErrorsPlugin(),
  ],
}
```

模块拆分的代码是这样的：

The code of Coding splitting is:

```js
export default {
  path: '/module-a',
  component: resolve => import('./main').then(resolve),
};
```

别的地方都是正常的 Vue 代码，编译后打开页面就发生了错误：
Other is normal code of vue, but occur error on opened page on browser:

```
[vue-router] Failed to resolve async component default: TypeError: Cannot read property 'call' of undefined
[vue-router] uncaught error during route navigation:
vendor.js:12545 TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (manifest.js:55)
    at Object.56 (1.js:151)
    at __webpack_require__ (manifest.js:55)
    at Object.55 (1.js:112)
    at __webpack_require__ (manifest.js:55)
    at Object.54 (1.js:75)
    at __webpack_require__ (manifest.js:55)
    at Object.49 (1.js:8)
    at __webpack_require__ (manifest.js:55)
    at <anonymous>
```

经过我的研究后发现，`style-loader` 的模块没有全部加载。并且在我监视代码变更的情况下，修改任何代码导致的 Webpack 重新编译，没有加载的模块会在重新编译后打包进去，上面的问题将被修复。

According my search, the modules of `style-loader` aren’t load for all. further, modify any code will be fixed the error on my server is oping with watch setting. And the module of not loaded on first compile, will be packed. The error was fixed.

这是我的[代码库](https://github.com/Lenic/vue-demo)，现在是运行正常的，只需要注释入口文件的[这一行](https://github.com/Lenic/vue-demo/blob/32f8f51f6a76acafc66adb338481afa5596988b2/src/client/index.js#L12)，即可复现这个 Bug。

This is [my coding responsitory](https://github.com/Lenic/vue-demo), and is normal now. Comment [this line](https://github.com/Lenic/vue-demo/blob/32f8f51f6a76acafc66adb338481afa5596988b2/src/client/index.js#L12), the bug will appear.

**Comment by evilebottnawi** [comment]
@Lenic Please use English language for describe your problems, it is standard for speaking on github.

**Comment by Lenic** [comment]
@evilebottnawi Chinese is English's translation, so it's OK read English only.

**Comment by evilebottnawi** [comment]
@Lenic Thanks, in near future i investigate this

**Comment by michael-ciniawsky** [comment]
`vue-router` and `vue-loader` (`vue-style-loader`) is a custom implementation, it's difficult to say where it fails if your a are unfamiliar with `vue-*` internals. Can you pin point the issue down a bit please (maybe without `vue`, but similiar approach)

**Comment by Lenic** [comment]
@michael-ciniawsky Look my [demo project](https://github.com/Lenic/classic-web), clone and run it, you can find error in chrome dev tool. Modify any code and save, the error will disappear by refresh the page.

**Comment by Lenic** [comment]
@michael-ciniawsky , Can you help me?

**Comment by evilebottnawi** [comment]
@Lenic just `children: true` to `CommonsChunkPlugin`, but seems it is issue in `webpack` inside `CommonsChunkPlugin`. Feel free to open issue in `webpack`. Thank you.

@webpack-bot move to `webpack/webpack`.
