### ISSUE TITLE
Flash of Unstyled Text. when my page jump to another page, and use 'style.unuse()' in componentWillUnmount(). 

### ISSUE THREAD

**Issue by msdlisper** [webpack-contrib/style-loader#267]
**What is the current behavior?**
when a page changed, I removed my styles use 'unuse()' in 'componentWillUnmount',  the browser  recalculated and  reflowed with no styles  before next page render, so, my page have a flash. important: this flash only find in Blink browser.  other browser have same problem only in break point.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
webpack: 3.6.0,  node: v6.8.1, react: 15.6.1

**Comment by michael-ciniawsky** [comment]
Won't fix from our side sry...
