### ISSUE TITLE
Edge Case: Window Undefined in WebWorker

### ISSUE THREAD

**Issue by shellscape** [webpack-contrib/style-loader#268]
**Do you want to request a *feature* or report a *bug*?**
A bug, but it's quite an edge case.

**What is the current behavior?**
When a bundle is compiled that is executed within a WebWorker and contains a css require (this is where it gets edgy), `window` isn't defined at all. That in turn, fails on [addStyles.js#23](https://github.com/webpack-contrib/style-loader/blob/67120f8dc831626f466d64513b4e26074e89341b/lib/addStyles.js#L23) with an error of `window is undefined` which would be expected.

**If the current behavior is a bug, please provide the steps to reproduce.**
With the refactor effort underway for webpack-dev-server@3.0.0, we tried to consolidate the files being built and how things were compiled, and ended up getting the index bundled by mistake with a secondary bundle that was for a WebWorker, in a particular example. It was unintentional and will be fixed, but still raised the issue.

webpack-dev-server was fixed up for WebWorkers in this commit https://github.com/webpack/webpack-dev-server/commit/70671ffdc2aa2bbe9483f20b00ac92f1b68f4dcb

**What is the expected behavior?**
Well, I can't say that there shouldn't be an error, given the context of this module is probably never intended for WebWorkers, but it would be a value add if it didn't attempt to execute within a WebWorker.

**Comment by michael-ciniawsky** [comment]
Both `window` && `document` are unavailable in `DedicatedWorkerGlobalScope`, so it isn't possible for `style-loader` to work within/from a worker context. The 'worker' bundle is generated by `worker-loader` and emitted as an asset (bundle), which `webpack-dev-server` is trying to serve ? If that's the case see https://github.com/webpack-contrib/worker-loader/blob/master/index.js#L31 which ensures 'worker' bundles are always named `[name].worker.js`. These `*.worker.js` files can be excluded and served as static asset. Any issue with the worker itself e.g CSS + DOM API usage is a user error 😛

**Comment by shellscape** [comment]
@michael-ciniawsky true. however, I think this is mislabeled as a bug, and I think the close was just a small smidgen premature. given that this should _never_ be used within a worker context, a very simple escape hatch should be considered; throwing a simple error alerting the using developer to the issue, and then bailing.

oodles of other dom-centric components will load successfully, but don't do squat within a worker context. unfortunately style-loader straight up fails on bundle load, if a bundle is erroneously using it in that context. I agree that it's user-error with the config, but that's not to say we can't be friendly to user to let them know of their mistake.

**Comment by robaweb** [comment]
Looks like i found this error in commit
https://github.com/webpack/webpack/commit/27e4d14a312d5f8bdf4118c2c028fb80b5df5f4b

**Comment by evilebottnawi** [comment]
@robaweb can you create issue in `webpack/webpack`?
