### ISSUE TITLE
Setup to force CSS to load before Javscript

### ISSUE THREAD

**Issue by HectorLS** [webpack-contrib/style-loader#269]
Hello,
I have a good webpack setup running right now for Development, the only problem is that CSS is loading after the Javascript in the browser, and then i got some ugly style issues in the first seconds on page load.

How can i force a load order
**packages**
```json
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.1",
    "babel-plugin-transform-react-jsx-img-import": "^0.1.4",
    "babel-preset-env": "^1.6.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "css-loader": "^0.28.4",
    "extract-text-webpack-plugin": "^3.0.1",
    "file-loader": "^0.11.2",
    "html-loader": "^0.5.0",
    "html-webpack-plugin": "^2.30.1",
    "node-sass": "^4.5.3",
    "postcss-loader": "^2.0.6",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.18.2",
    "webpack": "^3.8.0",
    "webpack-dashboard": "^1.0.0",
    "webpack-dev-server": "^2.9.2"
}

```
**webpack.config.js**
```javascript
import autoprefixer      from 'autoprefixer';
import DashboardPlugin   from 'webpack-dashboard/plugin';
import ExtractTextPlugin from 'extract-text-webpack-plugin';
import HtmlPlugin        from 'html-webpack-plugin';
import path              from 'path';
import webpack           from 'webpack';

const isProd = process.env.NODE_ENV === 'production';



//////////////////////// FILEPATH ///////////////////////
/////////////////////////////////////////////////////////
const imagesFolder = 'public/assets/img/',
      buildFolder  = 'dist',
      sourceFolder = 'src',
      PATHS = {
        build        : path.resolve(__dirname, buildFolder),
        src          : path.resolve(__dirname, sourceFolder),
        node_modules : path.resolve(__dirname, 'node_modules'),
        appJS        : path.resolve(__dirname, `${sourceFolder}/app.js`),
        indexHTML    : path.resolve(__dirname, `${sourceFolder}/index.html`)
      };



//////////////////////// PLUGINS ////////////////////////
/////////////////////////////////////////////////////////
const HtmlPluginOptions = {
  template: PATHS.indexHTML,
  minify: {
    collapseWhitespace: true
  },
  hash: true
};

const ExtractTextPluginOptions = {
  filename: '[name].bundle.css',
  disable: !isProd,
  allChunks: true,
  ignoreOrder: false
};

const devServerOptions = {
  contentBase: PATHS.build,
  compress: true,
  port: 6969,
  stats: 'errors-only',
  open: true,
  hot: true,
  openPage: ''
};

const pluginsDev = [
  new DashboardPlugin(),
  autoprefixer,
  new HtmlPlugin(HtmlPluginOptions),
  new ExtractTextPlugin(ExtractTextPluginOptions),
  new webpack.HotModuleReplacementPlugin()
];

const pluginsProd = [
  require('autoprefixer'),
  new HtmlPlugin(HtmlPluginOptions),
  new ExtractTextPlugin(ExtractTextPluginOptions)
];

var pluginsList = isProd ? pluginsProd : pluginsDev;



//////////////////////// LOADERS ////////////////////////
/////////////////////////////////////////////////////////
const postcss = {
  loader: 'postcss-loader',
  options: {
    sourceMap: 'inline',
    plugins() {
      return [autoprefixer({ browsers: 'last 3 versions' })];
    }
  }
};

const scss = {
  loader: 'sass-loader',
  options: {
    sourceMap: 'inline',
    includePaths: [PATHS.node_modules]
  }
}

const stylesDev  = ['style-loader', 'css-loader?sourceMap', postcss, scss];

const stylesProd = ExtractTextPlugin.extract({
  fallback: 'style-loader',
  use: ['css-loader', postcss, scss],
  publicPath: buildFolder
});

const styles = {
  test: /\.scss$/,
  use: isProd ? stylesProd : stylesDev
};

const javascript = {
  test: /\.(js|jsx)$/,
  use: 'babel-loader',
  exclude: /node_modules/
};

const images = {
  test: /\.(jpe?g|svg|png|gif)$/i,
  use: [
    `file-loader?name=${imagesFolder}[name].[ext]`
  ]
};

const html = {
  test: /\.(html)$/,
  use: {
    loader: 'html-loader',
    options: {
      attrs: ['img:src', 'link:href']
    }
  }
};



//////////////////////// WEBPACK ////////////////////////
/////////////////////////////////////////////////////////
const webpackConfig = {
  entry: {
    app: PATHS.appJS
  },
  output:  {
    path: PATHS.build,
    filename: '[name].bundle.js'
  },
  module: {
    rules: [javascript, styles, images, html]
  },
  resolve: {
    modules: [PATHS.src, 'node_modules'],
  },
  devServer: devServerOptions,
  plugins: pluginsList
};

export default webpackConfig;
```

**Comment by michael-ciniawsky** [comment]
Inject your `bundles` into the `head` of your HTML during development.`html-webpack-plugin` has an option for that.

**Comment by HectorLS** [comment]
If i update the `html-webpack-plugin` options like this

```javascript
const IndexHtmlOptions = {
  template: PATHS.indexHTML,
  filename: 'index.html',
  minify: {
    collapseWhitespace: true
  },
  hash: true,
  'files': {
    'css': [ '[name].bundle.css' ],
    'js': [ '[name].bundle.js'],
    'chunks': {
      'head': {
        'entry': '',
        'css': '[name].bundle.css'
      },
      'main': {
        'entry': '[name].bundle.js',
        'css': []
      },
    }
  }
};
```

yeah now css is on the head, but if i go to the browser's inspector i can see how my **.js** is loaded before the **.css**

Now this part, i think is a style-loader task right ?

**Comment by michael-ciniawsky** [comment]
CSS will be loaded after JS by design when using the `style-loader`. It adds the CSS as `<style></style>` tags to the DOM via **JS**. What I meant was the `inject` option of `html-webpack-plugin`

```
const IndexHtmlOptions = {
  template: PATHS.indexHTML,
  filename: 'index.html',
  minify: {
    collapseWhitespace: true
  },
  hash: true,
  inject: 'head', // <=
  'files': {
    'css': [ '[name].bundle.css' ],
    'js': [ '[name].bundle.js'],
    'chunks': {
      'head': {
        'entry': '',
        'css': '[name].bundle.css'
      },
      'main': {
        'entry': '[name].bundle.js',
        'css': []
      },
    }
  }
};
```

This might avoid some FOUC, but if your project exceeds a certain size and especially if sourcemaps are used, preventing FOUC will be difficult with the way `style-loader`works

**Comment by HectorLS** [comment]
I see..., now loads much better but i had the js in the head, so maybe this is a good approach to work in Dev mode, thank you so much

**Comment by mightym** [comment]
This is an interesting issue I lately stumbled over too. The fact that the JS injects the styles is a general problem for me too. It is very common to initially hide elements via css tranform. Like for example a navigation bar. And its a common practice to add a css transition on that element to animate it in and out. I realized on my latest react project using webpack style-loader and css modules that there is always an initial animation on those elements. This is because the css is actually available after the js, even worse when you use react an the DOM gets created via JS.

**Comment by gavinlynch** [comment]
same, @mightym.
And for my case, I often both create custom components or use libraries that rely on CSS-defined element dimensions when doing calculations for various things. It's a great way to avoid hardcoded values and so when a designer can tweak component styles without fear of breaking the component and involving a dev.

**Comment by mightym** [comment]
@gavinlynch give https://github.com/webpack-contrib/mini-css-extract-plugin a try. this will help you to have a more "classic" setup with an external css file

**Comment by sherryChen0206** [comment]
In my react project I get the same isssue. I start render in window.onload funtion.`const render = (Component) => {
	ReactDOM.render(
		<AppContainer>
			<Router>
				<Component />
			</Router>
		</AppContainer>,
		document.getElementById('root')
	);
};
window.onload = () => {
	render(FrameView);
};`

**Comment by mightym** [comment]
@sherryChen0206 use the plugin I proposed 
https://github.com/webpack-contrib/mini-css-extract-plugin its currently the only way to control it via a external css file. And to ensure that the CSS is loaded before the JS

**Comment by nike1231** [comment]
Hello everyone, can someone help me with the loading of this wordpress website ?

https://vedabooks.bg

I think it's the same issue, the wordpress theme is "storeship".

Is the plugin applicable here ?

The website is not mine, but I want to help the owner, he asked in another forum.

**Comment by AkhileshThite** [comment]
🚀 FIX: 
This `[mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin)` will load your CSS before JavaScript.

Step 1:
Install mini-css-extract-plugin
```bash
npm install --save-dev mini-css-extract-plugin
```

Step 2:
Add `const MiniCssExtractPlugin = require("mini-css-extract-plugin");` in `webpack.config.js`.

Step 3:
Add `plugins: [new MiniCssExtractPlugin()],` in `webpack.config.js`.

Step 4:
Add this under rules in `webpack.config.js`.
```javascript
      {
        test: /\.css$/i,
        use: [MiniCssExtractPlugin.loader, "css-loader"],
      },
```
That's it!

**Comment by jviel-beta** [comment]
This youtube tutorial is a great illustration/explanation of the `mini-css-extract-plugin` fix many have suggested:
https://youtu.be/JlBDfj75T3Y?t=33
