### ISSUE TITLE
[Question] What's the point of sourceMap: true

### ISSUE THREAD

**Issue by kud** [webpack-contrib/style-loader#271]
Hello,

When I activate sourceMaps, I've got this result:

```
Source map error: Error: sourceMapURL could not be parsed
Resource URL: blob:http://xxxx/b82d1808-4542-8b45-a829-b13f36458b84
Source Map URL: data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi9Vc2Vycy9rdWQvUHJvamVjdHMvX2NvbnRleHRlL2xvaXMtd2ViYXBwL3NyYy9zdHlsZXMvYm94LW1vZGVsLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTs7R0FFRztBQUNIO0VBQ0UsdUJBQXVCO0NBQ3hCOztBQUVEOzs7RUFHRSxvQkFBb0I7Q0FDckIiLCJmaWxlIjoiYm94LW1vZGVsLmNzcyIsInNvdXJjZXNDb250ZW50IjpbIi8qKlxuICogbW9yZSBpbmZvIHRoZXJlOiBodHRwczovL2RldmVsb3Blci5tb3ppbGxhLm9yZy9lbi9kb2NzL1dlYi9DU1MvYm94LXNpemluZ1xuICovXG5odG1sIHtcbiAgYm94LXNpemluZzogYm9yZGVyLWJveDtcbn1cblxuKixcbio6YmVmb3JlLFxuKjphZnRlciB7XG4gIGJveC1zaXppbmc6IGluaGVyaXQ7XG59XG4iXSwic291cmNlUm9vdCI6IiJ9
```

What sourceMaps in this loader should do?

**Comment by michael-ciniawsky** [comment]
Where does the source map posted come from ? Where does the Error come from ?

**Comment by kud** [comment]
I've no idea. I've just activated it and this is what I've got in the console of Firefox Nightly.

**Comment by evilebottnawi** [comment]
@kud seems bug in Firefox, can you create minimum reproducible test repo?

**Comment by kud** [comment]
I'm sorry, this is a @webpack-contrib-services / css-loader issue in fact.

**Comment by kud** [comment]
You can see my issue here: https://github.com/webpack-contrib/css-loader/issues/640


However, I don't see the point yet of sourceMap on THIS loader? Can you explain it to me please? O:)

**Comment by evilebottnawi** [comment]
@kud `css-loader` generate source maps, but you can not want to insert them, honestly it does not make much sense, but this is a standard practice for all loaders what can generate source maps.

**Comment by kud** [comment]
I mean source maps for style-loader, not css-loader where I can see the point as it shows the url of the css file. 

Or maybe did you make a mistake with the name of the loader you typed?

**Comment by evilebottnawi** [comment]
@kud oh yes, it is type, i mean `style-loader`

**Comment by evilebottnawi** [comment]
@kud when you use `sourceMap: true` for `style-loader` - you say what `style-loader` should insert soucr map url or content to `style` tag

**Comment by kud** [comment]
Ooooooooh, okay. Thank you!
