### ISSUE TITLE
querySelector don't support ie7

### ISSUE THREAD

**Issue by taven-liu** [webpack-contrib/style-loader#277]
when i upgrade style-loader to v0.19, it can't work in ie7, and v0.13 is ok. i don't know why removed the code for querySelector check

**Comment by evilebottnawi** [comment]
@taven-liu IE7 is deprecated, also webpack@3 don't support IE7, i think it is not ok support this browser. How solve this? Use polyfill, example https://gist.github.com/chrisjlee/8960575. Thank for issue.
