### ISSUE TITLE
The options.sourceMap don't work

### ISSUE THREAD

**Issue by qq20004604** [webpack-contrib/style-loader#280]
The description of sourceMap is: 'Enable/Disable Sourcemaps'.

But in fact, the file: `lib/addStyles.js` ,line 143, the value is not from options, but modules.

And of course, `options.convertToAbsoluteUrls` don't work either.

I try to use `css-loader`, and found that when `css-loader`'s options.Sourcemaps is true, `options.convertToAbsoluteUrls` will work.

version ``0.19.0`` from npm

**Comment by evilebottnawi** [comment]
@qq20004604 can you provide minimum reproducible test repo?

**Comment by qq20004604** [comment]
@evilebottnawi 
https://github.com/qq20004604/webpack-study/tree/master/5%E3%80%81Loader/style_loader_demo

**Comment by evilebottnawi** [comment]
@qq20004604 do you read https://github.com/webpack-contrib/style-loader#url note? Also can you describe what you expect.
Also source maps don't work because you use:
```js
{
    loader: 'css-loader',
    options: {
        sourceMap: false
    }
}
```
Just cache ` sourceMap: true`, because `css-loader` generate source maps, `style-loader` just add their for link. Thank for issue!
