### ISSUE TITLE
singleton, default is false, not true

### ISSUE THREAD

**Issue by qq20004604** [webpack-contrib/style-loader#283]
https://github.com/webpack-contrib/style-loader#singleton

> This option is on by default in IE9, which has strict limitations on the number of style tags allowed on a page. You can enable or disable it with the singleton option.

But in fact, singleton default is false, not true.

DEMO: https://github.com/qq20004604/webpack-study/tree/master/5%E3%80%81Loader/style_loader_demo

**Comment by evilebottnawi** [comment]
@qq20004604 hm, you are right, let's fix it

**Comment by evilebottnawi** [comment]
Done in https://github.com/webpack-contrib/style-loader/pull/285
