### ISSUE TITLE
export an 'onload' callback

### ISSUE THREAD

**Issue by deemstone** [webpack-contrib/style-loader#287]
**request a *feature***

Let me know  when the css file loaded.

**What is the current behavior?**

require()  and wait , and dont know how long to wait...

**What is the expected behavior?**

Whatever callback style, promise / callback / event ....
Example:
```
var onload = require('style-loader!css-file.css');
onload( () => { /* DO My Job... */ })
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

We use style-loader in async loaded chunk, which will loaded when user need it.
But depends on http response time cost, there would be some time no style when page rendering.
If we could get an onload calback, it will be more reliable.

**Comment by evilebottnawi** [comment]
@deemstone can you send PR?

**Comment by axelson** [comment]
Is there any work-around for this besides a setTimeout with a large delay?

**Comment by mancontr** [comment]
When using React, there is only one render for a whole component tree, but each component might be in a separate file and have a require for its styles. If we want to make sure all styles from a chunk are applied before rendering that chunk's tree, it might be useful to have something like an "all styles from chunk have been applied" event we can catch globally, in addition to what might be implemented for each require.

We're using style-loader in devMode and we're getting a FOUC after initial render but before styles get applied. We'd like to wait until styles loaded before doing the render, and the event would make it very easy. It might help with async loading of routes too, but we don't have much experience with that part.

**Comment by gianpesto** [comment]
@axelson you could use something like this:

in ur webpack.config
`
...
{
    loader: 'style-loader',
    options: {
        attrs: { 'data-styles-loaded': 'true' }
    }
},`

wait for styles 
`
export default function waitForStyles(){
  return new Promise( (resolve, reject) =>{

    const interval = setInterval( () =>{
      let counter = 0;

      if (typeof document.querySelector('[data-styles-loaded]') !== null){
        clearInterval(interval);
        resolve();
      }
      
      if(counter > 10) {
        clearInterval(interval);
        reject('styles timeout'); 
      }

      counter++;
    }, 500)
  })
}
`

**Comment by evilebottnawi** [comment]
Sorry out of scope `style-loader`, we don't create `link` tag, so no `onload`, if you need to loading styles asynchronously you can use `import().then()`
