### ISSUE TITLE
The loader doesn't return contents of stylesheet

### ISSUE THREAD

**Issue by Manidos** [webpack-contrib/style-loader#289]
With the following configuration I can't get ahold of the contents of `style.css`.
`console.log(style)` gives me an empty object `{ }`. Is it a bug or a normal behaviour?

**webpack.config.js**
```
var path = require('path');

module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'script.js'
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          { loader: 'style-loader'},
          { loader: 'css-loader'}
        ]
      }
    ]
  }
}
```
**src/index.js**
```
import * as style from './style.css'
const test = () => {
  console.log(style)
}
test()
```

**Comment by fabbballin** [comment]
Try this as your import statement: `import styles from './style.css'`

**Comment by fabbballin** [comment]
Do you have any styles defined in style.css? `{}` implies no styles and is expected behavior.

**Comment by michael-ciniawsky** [comment]
That's normal behavior since the CSS will be added via a `<style></style>` to the DOM and is therefore removed from the module exports. The empty `{Object}` is for locals (CSS Modules) if you use them
