### ISSUE TITLE
style-loader does not working after css is extracted.

### ISSUE THREAD

**Issue by sasssssha** [webpack-contrib/style-loader#301]
Greetings
My style-loader is set as fallback and in dev mode extract-text-plugin is disabled.
What is interesting, when I don't bundle my project and extract all files in dist folder, everything works fine, I can see `<style></style>` tag(which is arranged right after link to compiled css). But when I build my project and try to run it in dev mode, everything is extracted in dist folder, and I see only `link` to bundled css in `head`.

E.g.
running in dev mode: 
`<head>`
`<link rel="stylesheet" href="static/css/styles.css"> //it's not working because css is not extracted` 
`<style type="text/css">...</style>`
`</head>`

build&extract and then running in dev mode: 
`<head>`
`<link rel="stylesheet" href="static/css/styles.css"> //it's working now`
`</head>`
`// no style-tag`

I think that somehow webpack sees that styles is already extracted and it's not necessary to include `style` tag. But actually it does not matter if configuration says that tag should be included.
Does anybody have any idea about what's going on? Thanks in advance!

**Comment by sasssssha** [comment]
I temporary solved this problem by removing `dist` folder before running in dev mode but problem still exists.

**Comment by michael-ciniawsky** [comment]
I don't fully understand your config, could please show your `webpack.config.js` ?  `extract-text-webpack-plugin` 's `fallback` only 'works' in case extracting fails.

**Comment by sasssssha** [comment]
```
const path = require('path')
const webpack = require('webpack')
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');

const extractSASS = new ExtractTextPlugin({
  filename: './css/styles.css',
  allChunks: true,
  disable:process.env.NODE_ENV == "production" ? false : true
});

var entry = [
  'babel-polyfill',
  './src/index.js'
]

var output = {
  path: path.join(__dirname, 'dist'),
  filename: 'js/bundle.js',
  publicPath:'/static/'
}

var rules = [
  {
    use: 'babel-loader',
    include: __dirname,
    exclude:[
      path.resolve(__dirname, "node_modules"),
    ],
    test: /\.js$/
  },
  {
    test: /\.(scss|css)$/,
    use: extractSASS.extract({
        fallback: 'style-loader',
        use: ['css-loader','sass-loader']
    })
  },
  {
    test: /\.(png|jpg|gif)$/,
    use: [
      {
        loader: 'file-loader',
        options: {
          outputPath:'img/',
        }
      }
    ]
  }
]

if(process.env.NODE_ENV != 'production') entry.push('webpack-hot-middleware/client')

const dev = {
  devtool: 'cheap-module-eval-source-map',
  entry: entry,
  output: output,
  plugins: [
    extractSASS,
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.HotModuleReplacementPlugin()
  ],
  module: {
    rules: rules
  }
}

const prod = {
  entry: entry,
  output: output,
  plugins: [
    extractSASS,
    new webpack.optimize.OccurrenceOrderPlugin(),
    new CopyWebpackPlugin([{from:'src/img', to:'img'}]),
    new webpack.optimize.UglifyJsPlugin(),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV)
    })
  ],
  module: {
    rules: rules
  }
}

module.exports = process.env.NODE_ENV == 'production' ? prod : dev;
```

**Comment by michael-ciniawsky** [comment]
```js
const env = process.env.NODE_ENV || 'development'
...
{
    test: /\.(scss|css)$/,
    use: env === 'production' 
      ? extractSASS.extract({
          fallback: 'style-loader',
          use: ['css-loader','sass-loader']
        })
      : [ 'style-loader', 'css-loader', 'sass-loader']
}
```

Don't use the `disable` option, it's bad practice in general and won't work in your case

**Comment by sasssssha** [comment]
The problem still appears, the same thing. if css is extracted, style loader is not working

**Comment by michael-ciniawsky** [comment]
Both at the same time is not possible. Why do you want to load the styles twice ? Please always include your current `webpack.config.js` so it's easier to follow

**Comment by sasssssha** [comment]
I return plain html from the server(in future it will be necessary because of server-rendering) and styles are included.
When I use dev mode, i want to use style tag. When I bundle files, I want to have compiled sass, included in my returned string. So, I simply include css from dist folder to my returned html. If exists - okay, include it, if no - we have style tag. But when I have compiled dist folder and my final css which included in html, I can't see any style tag in dev mode. Hope it makes sense...

**Comment by sasssssha** [comment]
For some reason I can't use style tag in presence of css file.

**Comment by michael-ciniawsky** [comment]
> So, I simply include css from dist folder to my returned html. If exists - okay, include it, if no - we have style tag. But when I have compiled dist folder and my final css which included in html, I can't see any style tag in dev mode. Hope it makes sense...

If the `extract-text-webpack-plugin` is used/applied the `style-loader` code won't be added to the bundle and there are no `<style></style>` tags injected via JS because the CSS is already extracted into a separate file. It's an either `<style>` or <link href="bundle.css">`. The option name `fallback` maybe misleading here, it's only used if `extract-text-webpack-plugin` throws an `{Error}` during extraction and **then** tries to use the `style-loader` instead (no separate file). There is no way for `style-loader` && `extract-text-webpack-plugin` to determine your use case, since this seems to happen during runtime (after `webpack`)

**Comment by sasssssha** [comment]
Why style loader does not work if css exists is not clear for me

**Comment by sasssssha** [comment]
Yep

**Comment by sasssssha** [comment]
oh, it's working now.
I simply changed
```
const extractSASS = new ExtractTextPlugin({
  filename: './css/styles.css',
  allChunks: true
});
```

to

```
const extractSASS = new ExtractTextPlugin({
  filename: './css/[name].css',
  allChunks: true
});
```

Many thanks for your attention, Michael
