### ISSUE TITLE
sourceMap: true <link> tag cannot load url() asset on Chrome

### ISSUE THREAD

**Issue by wxlworkhard** [webpack-contrib/style-loader#302]
Why use `<link>` replace `<style>` when `sourceMap: true` ? `<link>` cannot load `url()` asset on Chrome. 

Why not just use
```
css += "\n/*# sourceMappingURL=data:application/json;base64," +
            btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap)))) + " */";
``` 
and 

```
styleElement.appendChild(document.createTextNode(css));
```
in addStyles.js file. This is simple and have no problem.

**Comment by evilebottnawi** [comment]
@wxlworkhard Can you describe your problem more verbosely, better create minimum reproducible test repo?

**Comment by wxlworkhard** [comment]
Set `sourceMap: true`.

HTML file content is
![image](https://user-images.githubusercontent.com/8287140/36578235-d7c6573a-1896-11e8-8c37-f6d6dfb5c446.png)

CSS files content are
![image](https://user-images.githubusercontent.com/8287140/36578602-4e17fbbc-1899-11e8-855d-da820b39b392.png)
and
![image](https://user-images.githubusercontent.com/8287140/36578626-6d7381f2-1899-11e8-841b-47616f08b4b7.png)

Image resource can load but font resource cannot load
![image](https://user-images.githubusercontent.com/8287140/36578707-ea0dbb7e-1899-11e8-9160-28fc275e81a1.png)

Use `<style>` replace `<link>` is no problem.

HTML file content is
![image](https://user-images.githubusercontent.com/8287140/36578789-768996ea-189a-11e8-971a-03e278a6ae83.png)

![image](https://user-images.githubusercontent.com/8287140/36578846-c25cc1c8-189a-11e8-9102-5578ab03612e.png)

**Comment by evilebottnawi** [comment]
@wxlworkhard all resources loaded in all browsers. Maybe you have invalid `publicPath` for fonts, check you configuration. Also please create reproducible test repo if problem still exists. Thanks!
