### ISSUE TITLE
__webpack_nonce__ support or alternative way of solving CSP?

### ISSUE THREAD

**Issue by madjam002** [webpack-contrib/style-loader#306]
I'm looking at using Webpack on a site which requires strict Content Security Policy headers.

I'm setting `window.__webpack_nonce__` but it doesn't seem to be adding a `nonce` attribute to `style` elements created by style-loader. Looking at webpack#3210 it only seems to be adding a nonce attribute to generated script elements? Is there some additional work required in style-loader to support nonce attributes?

I don't mind doing a PR, just wanted to make sure first though that I'm not missing something!

**Comment by madjam002** [comment]
Just to add as well, I've noticed some discussion in #155 regarding CSP, but the way that custom attributes has been implemented there isn't suitable for nonce values as nonce values need to be secure cryptographically generated random strings for each page load and not hard coded into the build

**Comment by jwbay** [comment]
The way aphrodite solves this is to look for an existing style tag before generating one. In their case something like `<style data-aphrodite>`. This effectively solves CSP because you can provide a style tag with a nonce already attached.

**Comment by iamdavidfrancis** [comment]
Has there been any progress on this? I'm also working on a site with a strict CSP.
 It doesn't seem like it would be a huge PR to support __webpack_nonce__

**Comment by evilebottnawi** [comment]
PR welcome :+1:

**Comment by plondon** [comment]
I think this can be closed now since #319 has been merged and included in 0.22.0

**Comment by plondon** [comment]
Also fyi @madjam002 you'll want to just set `__webpack_nonce__` and **not** `window.__webpack_nonce__`. Also do not try to do this with hot module reloading.

**Comment by evilebottnawi** [comment]
@plondon can you send PR to README about this?

**Comment by alshdavid** [comment]
What's the status with this?

Can I use style_loader with a nonce?
Is there anything special I need to do?
Will it read my window.__webpack_nonce__?
Will it work with dynamic imports?

**Comment by plondon** [comment]
> What's the status with this?
> Resolved but confusing docs?
> Can I use style_loader with a nonce?
Yes
> Is there anything special I need to do?
Make sure the files where you set the nonce is one of the very first imports in the project:
See: create-nonce.js (https://github.com/blockchain/blockchain-wallet-v4-frontend/blob/development/packages/blockchain-wallet-v4-frontend/src/create-nonce.js#L4) is then imported from the first main entry point index.js (https://github.com/blockchain/blockchain-wallet-v4-frontend/blob/0477f60e62b3635ef00db3338319c939506c8756/packages/blockchain-wallet-v4-frontend/src/index.js)
> Will it read my window.__webpack_nonce__?
No
> Will it work with dynamic imports?
Yes

**Comment by evilebottnawi** [comment]
@plondon maybe you can send a PR to docs ? :smile: anyway thanks for answer

**Comment by caub** [comment]
@plondon > you'll want to just set __webpack_nonce__ and not window.__webpack_nonce__

What's the difference?

**Comment by theKashey** [comment]
As many other "magic variables" webpack will transform `__webpack_nonce__` to `__webpack_require__.nc`. Please refer to https://github.com/webpack/webpack/blob/1ed8aaf2e291fc0b14597ef452e6224ad10ccbc9/lib/RuntimeGlobals.js#L161

So the result of complication will be
```ts
__webpack_require__.nc = '..';
window.__webpack_nonce__ = '..';
globalThis.__webpack_nonce__ = '..';
```
But only if complied with webpack. Without it these lines are equal.
