### ISSUE TITLE
Webpack 4: incorrect peer dependency

### ISSUE THREAD

**Issue by winterbe** [webpack-contrib/style-loader#307]
Hi,

when using `style-loader` with Webpack 4 you get this warning:

`warning "style-loader > schema-utils@0.4.3" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".`

Could you please bump version of dependency `schema-utils` to `^0.4.5` in order to fix this issue?

Thanks.

**Comment by michael-ciniawsky** [comment]
Will do when I gave a few minutes, PR welcome

**Comment by winterbe** [comment]
See PR #308
