### ISSUE TITLE
inesertInto not working with insertAt

### ISSUE THREAD

**Issue by Vasikaran** [webpack-contrib/style-loader#313]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Throwing issue when I use these at the same time.

**If the current behavior is a bug, please provide the steps to reproduce.**
My gist to explain this issue. https://gist.github.com/Vasikaran/a1bfc07cfbb5f1eb603af06f1f7f1673

**What is the expected behavior?**
Check insertInto's type then handle that by type.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

Webpack - 3.5.4
Node JS - 8.10.0
OS - MacOS 10.13.3

**Comment by evilebottnawi** [comment]
Already fixed in master
