### ISSUE TITLE
Transform not applied during HMR update

### ISSUE THREAD

**Issue by labriola** [webpack-contrib/style-loader#321]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
on HMR, defined transform functions are not applied to the reloaded content

**If the current behavior is a bug, please provide the steps to reproduce.**
Defined a style-loader, use webpack dev server, and make a change to the css. The css will be injected raw and never passed through the transform function.

**What is the expected behavior?**
I think that the transform should likely be applied to subsequent replacements else the first and nth load have potentially different CSS

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
Webpack 4.x. Core issue seems to be that only addStyle applies the transform and that updateStyle does not.

**Comment by evilebottnawi** [comment]
option transform was removed without replacement
