### ISSUE TITLE
If transform function yeileds a falsey value, it is ever allowed to yield css for the same module in subsequent HMRs

### ISSUE THREAD

**Issue by labriola** [webpack-contrib/style-loader#324]
Discovered this while fixing 321.

In addStyles() addStyle/updateStyle once a transform function evaluates to false, a noop function is assigned to that handle that module from this point forward. Should the transform function on the net HMR yield something truthy, it's too late and the CSS will never be re-evaluated.

I took a stab at fixing it, but it is going to require a lot more refactoring due to the way those functions are presently constructed with the update() method. Please see Issue 321 for more detail.

Trying to log this here in case anyone has the issue.

**Comment by evilebottnawi** [comment]
@labriola can you provide links on function? Also do you have ideas how we can fix it?

**Comment by labriola** [comment]
https://github.com/webpack-contrib/style-loader/blob/e4fa68a19d2390e265e27ec60ae928bf80a41228/lib/addStyles.js#L248

Basically, instead of returning a function that does nothing, we need to return something that can still handle an update and retest if the transform will in fact produce something truthy. Ideally, we would also want to do this without running the function multiple times, which is tricky given the way the implementation of addStyles handles flow control. The update function at the bottom of the function I linked (line 287) is close, but it relies upon the fact that update was set to one of several functions above it, so it can't be relocated. 

Right now what happens is that, after a falsey is returned from the transform, every subsequent reload of that module is nooped out via line 248. One has to be extremely careful though as this function (or any other returned) is subsequently called during any cleanup but with no arguments.

https://github.com/webpack-contrib/style-loader/blob/e4fa68a19d2390e265e27ec60ae928bf80a41228/lib/addStyles.js#L109

The existing addStyle functions all rely upon this behavior as they handle various cases where they may not get the expected object.

Side note, the other thing making this really hard to test is that addStyles maintains internal state. One example, is line 6. While trying to debug this and write tests for the other PR its been a non-stop problem as test work in a vacuum and fail when run together due to retained stated.

**Comment by evilebottnawi** [comment]
option transform was removed without replacement
