### ISSUE TITLE
Allow importing code to determine where styles are inserted

### ISSUE THREAD

**Issue by grommett** [webpack-contrib/style-loader#328]
This is a feature request.

### Problem

As far as I can tell, the style loader only allows for styles to be inserted into one location, either the `<head>` or where specified in the `inserInto` string or function.

This approach does not work with composed/nested custom elements, as each can have their own shadow dom. If, for example,  `insertInto` specifies the root custom element the styles are not picked up in children shadow doms.

### Feature Request
Allow importing code to determine where styles are inserted.

### Possible Solution
1. Add an `option` for local insertion. Let's call it `localInsert`, which defaults to `false` so that code executes as it currently does.
2. When `localInsert` is `true`, the `update` function is not invoked and we attach a method (`localInsertTo` ?) to `exports`, which allows for the importing file(s) to determine where the styles are inserted.

### Example
In the example below each custom element will have their imported styles inserted into their respective shadow doms by calling the `localInsertTo`.

`Webpack`
```js
...
options: {
  localInsert: true
}
...
```

`Parent`
```js
import css from './parent.css';

export class Parent extends HTMLElement {
  constructor() {
    super();
    this.shadow = this.attachShadow({ mode: 'open' });
    this.shadow.innerHTML = `
    <div>Parent 
      <x-child></x-child>
    </div>`;
    css.localInsertTo(this.shadow);
  }
}

customElements.define('x-app', Parent);
```

`Child`
```js
import css from './child.css';

export class Child extends HTMLElement {
  constructor() {
    super();
    this.shadow = this.attachShadow({ mode: 'open' });
    this.shadow.innerHTML = `<div>child</div>`;
    css.localInsertTo(this.shadow);
  }
}

customElements.define('x-child', Child);
```

**Comment by bcanseco** [comment]
Having the exact same issue, this would be an awesome feature!

**Comment by grommett** [comment]
@bcanseco 
If you're interested I played with this idea and actually got it working. I'm not sure if it meets your use case, but have a look at the code in the repo I was playing with it in.

**Loader files are here**: https://github.com/grommett/web-components/tree/master/html-loader-css-modules/loaders

**Usage(webpack.config)** here:
https://github.com/grommett/web-components/blob/master/html-loader-css-modules/webpack.config.js

**Comment by evilebottnawi** [comment]
We have useable api, i think we need improve this, adding more option for `style.use()` or maybe implement new api, it should be easy, so PR welcome, anyway will be implemented for `2.0.0` version

**Comment by evilebottnawi** [comment]
For better compatibility with css modules from w3 spec (not to be confused with css-modules from `css-loader`), we need export `styles` as `String` and do:

```js
import customSquareStyles from './custom-square.css';

class CustomSquare extends HTMLElement {
  // Specify observed attributes so that
  // attributeChangedCallback will work
  static get observedAttributes() {
    return ['l'];
  }

  constructor() {
    // Always call super first in constructor
    super();

    this.attachShadow({ mode: 'open' });
  }
  connectedCallback() {
    const div = document.createElement('div');

    this.shadowRoot.appendChild(div);

    const bgPurple = new CSSStyleSheet();

    bgPurple.replace(`div { 
    background: purple; 
    width: ${this.getAttribute('l')}px;
    height: ${this.getAttribute('l')}px;
}`);

    this.shadowRoot.adoptedStyleSheets = [bgPurple];
  }
}

customElements.define('custom-square', CustomSquare);
```

**Comment by mike-shtil** [comment]
> For better compatibility with css modules from w3 spec (not to be confused with css-modules from `css-loader`), we need export css `styleSheet` as `String` and do:
> 
> ```js
> import styles from './custom-square.css';
> 
> class CustomSquare extends HTMLElement {
>   // Specify observed attributes so that
>   // attributeChangedCallback will work
>   static get observedAttributes() {
>     return ['l'];
>   }
> 
>   constructor() {
>     // Always call super first in constructor
>     super();
> 
>     this.attachShadow({ mode: 'open' });
>   }
>   connectedCallback() {
>     const div = document.createElement('div');
> 
>     this.shadowRoot.appendChild(div);
> 
>     const bgPurple = new CSSStyleSheet();
> 
>     bgPurple.replace(styles);
> 
>     this.shadowRoot.adoptedStyleSheets = [bgPurple];
>   }
> }
> 
> customElements.define('custom-square', CustomSquare);
> ```

This looks like an elegant approach, however `import styles from './custom-square.css'` would only return a map of key:classname, not the compiled CSS string. Am I missing something?

**Comment by evilebottnawi** [comment]
@mike-shtil it is only return css nothing more, for better w3c compatibility with css modules spec (do not confuse with css modules from css-loader)

**Comment by alexander-akait** [comment]
There are two solution fr shadow DOM:
- https://github.com/webpack-contrib/style-loader#function, I will move this to example
- https://github.com/webpack-contrib/css-loader/pull/1368 will be finished today/tomorrow (no need style-loader, but require `CSSStyleSheet` support, you can polyfill this, I will provide example in css-loader), note for HMR you need to write it manually, I will provide small example too

Original style-loader `styleTag` and `singletonStyleTag` is not designed for this case, in theory it is possible using hacks, but better avoid it
