### ISSUE TITLE
Source maps don't work 

### ISSUE THREAD

**Issue by Deathangel908** [webpack-contrib/style-loader#329]
I'm trying to configure source maps, but ithey doesn't work:
**webpack.config.js**;
```
{
  entry: "./main.css",
  devtool: '#source-map',
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          {
            loader: 'style-loader',
            options: {
              sourceMap: true,
              convertToAbsoluteUrls: true
            }
          },
          "css-loader",
        ]
      },
    ],
  },
};
```
***main.css**
```
body {
	background-color: green;
}
```

![image](https://user-images.githubusercontent.com/1336703/41589934-78373f2c-73be-11e8-9f1d-e10518da2e88.png)

What I expect to see there is `main.css:2`

[Here's the minimal github example](https://github.com/Deathangel908/sass-loader-css-modify-issue) . To reproduce:
 - npm install
 - npm run dev

p.s.
I'm using Archlinux, and Chrome 67. I also checked firefox, it's the same. I'm not sure how styles source maps should work, I assume they should include `/*# sourceMappingURL*/` in the end, but it's missing. Also if I replace `style-loader` with [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) source map work perfectly.

**Comment by evilebottnawi** [comment]
@Deathangel908 please add option ` sourceMap: true,` for `css-loader`, feel free to feedback

**Comment by Deathangel908** [comment]
Ok thank you, my bad, but this was tricky.

 Maybe we should consider adding a note to README.md? Atm `sourceMap` present in `style-loader` section, but it's required only by `css-loader`.  Also other loaders like [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) don't require `sourceMap` to be present on `css-loader` to make it work.

 This could save other folks time who face the same issue.

**Comment by evilebottnawi** [comment]
@Deathangel908 PR welcome
