### ISSUE TITLE
How do you configure the global stylus file?

### ISSUE THREAD

**Issue by NewPrototype** [webpack-contrib/style-loader#330]
Some global variables are configured, and I think other stylus can use them, how do I do that?

**Comment by evilebottnawi** [comment]
@NewPrototype how stylus related to style-loader?

**Comment by NewPrototype** [comment]
Hello, I'm in webpack configuration loader to parse of stylus, but I don't know how to configure global stylus file, currently used are introduced each stylus global stylus file, but it is not simple

**Comment by evilebottnawi** [comment]
style-loader not related to `stylus` or other preprocessors, please create issue in `stylus-loader` repo, thanks!
