### ISSUE TITLE
'style-loader/url'  doesn't load the styles when configured with 'file-loader' and 'css-loader'

### ISSUE THREAD

**Issue by AlexanderLoshkarov** [webpack-contrib/style-loader#335]
> **Bug Report**

**What is the current behavior?**

'style-loader/url'  doesn't load the styles when configured with 'file-loader' and 'css-loader'

> ***.css**
 has this content:

```
exports = module.exports = require("./node_modules/css-loader/lib/css-base.js")(false);
// imports


// module
exports.push([module.id, ".template-hOne-19pIQ { font-weight: bold; color: red; }", ""]);

// exports
exports.locals = {
	"hOne": "template-hOne-19pIQ"
};
```

> ***.html**
contains:

`<div>Hello World</div>`

**If the current behavior is a bug, please provide the steps to reproduce.**

> **config**

  ```
  rules: [
      {
        test: /\.css$/,
        use:[
        { loader: 'style-loader/url' },
        { 
          loader: "file-loader",
          options: {
            name: './[path][name].[ext]'
          }
        },
        {
          loader: 'css-loader',
          options: {
            localIdentName: '[path][name]-[local]-[hash:base64:5]'
          }
        }
      ],
        exclude: /node_modules/
      },
      {
        test: /\.(js|jsx)$/,
        loaders: [ 'babel-loader', ],
        exclude: /node_modules/
      }
    ]
```

**What is the expected behavior?**
> ***.css**
contains:

`.template-hOne-19pIQ { font-weight: bold; color: red; }`

> ***.html**
`<div class="template-hOne-19pIQ">Hello World</div>`

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

"name": "webpack",
"version": "3.12.0",

node -v
v10.6.0

Windows

**Comment by evilebottnawi** [comment]
@AlexanderLoshkarov and what you expected? All works as expected

**Comment by AlexanderLoshkarov** [comment]
@evilebottnawi I expect to see css class names and styles in *.css, but in fact there is JavaScript code.
Is that the expected result?

**Comment by evilebottnawi** [comment]
@AlexanderLoshkarov `css-loader` makes from `css` `js` module (resolving `url` and `@import`), `style-loader` just load this module in browsers using `blob`. 

if you want send something to style-loader you should export this in loader before. You can look on `css-loader` and create own based on their logic. All bundlers work using same logic - `css` -> `js` -> `loader/extract`

**Comment by evilebottnawi** [comment]
Also don't use `style-loader/url`, it is load `js` module into `link` (no export provided) https://github.com/webpack-contrib/style-loader#url

**Comment by AlexanderLoshkarov** [comment]
@evilebottnawi sorry for my uncertain questions I'm a bit new in this stack.
But the only way I see as of now to have a modular css is to use 

> style-loader+css-loader

but this tandem expose the styles into `<style>css styles come here</style>` and obviously after some while I will end up with index.html full of css styles, which I don't want to.

Is there any solution to put those styles into the file and expose `<link href="bundled.css" />` ?

I thought 

> style-loader/url+file-loader+css-loader

meant to do this, but in all of the sadden it is not.

Thanks!

**Comment by achilsowa** [comment]
> Also don't use `style-loader/url`, it is load `js`(contains `css`) module into `link` (no export provided, just create runtime code and insert link) https://github.com/webpack-contrib/style-loader#url

I'm having the same problem as @AlexanderLoshkarov . When I use style-loader + css-loader [ for css ] and file-loader for [ for font] I can extract the font in the css file, but file is added in <style /> tag.

On the other hand if I use style-loader/url + file-loader the css is now included in <link /> ( which is what I want) but the fonts are no more extracted from css files.

So is it possible to have both, ie css included in <link /> and font extracted from css ?
