### ISSUE TITLE
Bump style-loader version to 1.0

### ISSUE THREAD

**Issue by edmorley** [webpack-contrib/style-loader#340]
Hi!

Would it be possible to bump style-loader's version to 1.0?

The reason being is that new features are being added as minor version bumps (eg `0.22.0` added a new feature but no breaking changes compared to `0.21.0`) - but the semver spec says that for versions under 1, these minor version bumps have to be treated as breaking changes. 

This means that I can't just refresh my lockfile to pick up new features, when using `^0.22.1` etc, and so Renovate has to open a new PR each time, eg:
https://github.com/mozilla-neutrino/neutrino-dev/pull/1016

I see there is a `next` branch, which presumably isn't ready yet - but that could be released as version 2 (version numbers are cheap :-)).

Many thanks :-)

**Comment by evilebottnawi** [comment]
@edmorley in our plans release `1.0.0` in this month. We should remove some legacy options and refactor code. It is already in roadmap.

/cc @michael-ciniawsky let's start work on this, `css-loader` will be release in nexr future

**Comment by michael-ciniawsky** [comment]
I'm +1 one on this in general, but with dropping some weird options beforehand etc

@evilebottnawi We should use Github Projects (per repo and/or org) or the like to define a roadmap and then start working on it. 

A general (roughly) process about how we organize should be put in place imho, but lets discuss via slack separately :)

**Comment by felixfbecker** [comment]
Could all other non-breaking releases please be released as only bumping the patch version? Tools consider minor version increments in 0.x.x versions breaking versions.

**Comment by evilebottnawi** [comment]
Will be doe in near future (this week), thanks for issue
