### ISSUE TITLE
dynamic css namespace option

### ISSUE THREAD

**Issue by brewster1134** [webpack-contrib/style-loader#344]
i was looking for a way to nest imported css into a unique namespace/parent css class/id. i have a problem enforcing properly isolating css from various components, and looking for a programmatic way to prevent cross-contamination.

something like...

###### **_foo.css_**
```css
div {
  background-color: red;
}
```

###### **_foo.js_**
```javascript
import foo.css
```

that would render...

```html
<style>
  .foo {
    div {
      background-color: red;
    }
  }
</style>
```

**Comment by evilebottnawi** [comment]
please use `postcss-loader` and https://github.com/radvalentin/postcss-prefix-selector#readme plugin for this purpose
