### ISSUE TITLE
Does style-loader still takes sourceMap option?

### ISSUE THREAD

**Issue by x-yuri** [webpack-contrib/style-loader#346]
**Do you want to request a *feature* or report a *bug*?**

Supposedly, documentation bug.

From what I can see, `style-loader` adds source map whenever it is [present][1] these days. Regardless of the value of `sourceMap` option. If that's the case the documentation and validation needs to be updated.

[1]: https://github.com/webpack-contrib/style-loader/blob/v0.23.0/lib/addStyles.js#L386-L389

**What is the current behavior?**

With `sourceMap: false` validation passes and source map is added to css code.

**What is the expected behavior?**

Validation fails. Updated documentation.

**Comment by evilebottnawi** [comment]
@x-yuri `sourceMap: false` should don't add source map, can you create minimum reproducible test repo?

**Comment by x-yuri** [comment]
@evilebottnawi [Here][1] you are.

[1]: https://github.com/x-yuri/example-style-loader-source-map
