### ISSUE TITLE
Respect semver?

### ISSUE THREAD

**Issue by kud** [webpack-contrib/style-loader#348]
Hello,

I'd like to know if it's possible to respect semver in your versions?

Because:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/655838/46422909-a0d04d00-c735-11e8-9652-ab7410e16f8f.png">

**Comment by evilebottnawi** [comment]
@kud we respect semver, just version less than 1.0.0, please read https://semver.org/

**Comment by kud** [comment]
Well it depends on what you think about this part: https://semver.org/#how-do-i-know-when-to-release-100

But maybe I should report this to npm-check so.

**Comment by evilebottnawi** [comment]
@kud right now we have good api, but it is not stable, in theory we can change api, but it is unlikely, we don't start with `1.0.0` due historical reason
