### ISSUE TITLE
How to to inject the style into a virtual Iframe 

### ISSUE THREAD

**Issue by jinyang1994** [webpack-contrib/style-loader#351]
With https://github.com/ryanseddon/react-frame-component or some other tech we're still working on.

#135 It doesn't seem to have solved the problem

**Comment by evilebottnawi** [comment]
Why it is doesn't work for you? Please provide example and config where it is not work

**Comment by jinyang1994** [comment]
I have multiple iframe, I want to insert into it head. The right way to use it?

**Comment by evilebottnawi** [comment]
@jinyang1994 just add `id` and difference `class` to `iframe`

**Comment by jinyang1994** [comment]
```javascript
{
  loader: 'style-loader',
  options: {
    insertInto: () => document.querySelector("#root"),
  }
}
```

How to insert into multiple iframe?

**Comment by evilebottnawi** [comment]
You need more complex logic here if you have multiple `iframe`, sorry i can't write logic for you

**Comment by jinyang1994** [comment]
```jsx
import React from 'react';
import Frame from 'react-frame-component';

<Frame className="iframe" name="test">
  <Test />
</Frame>

<Frame className="iframe" name="test">
  <Test />
</Frame>
```

```javascript
{
  loader: 'style-loader',
  options: {
    insertInto: () => document.querySelector(".iframe"),
  }
}
```

Use it like this?

**Comment by jinyang1994** [comment]
![image](https://user-images.githubusercontent.com/15340367/48835789-034fdc00-edbc-11e8-93e5-ea518b6adf60.png)
But it is not working. I'm going to create a simple example, wait a minute.

**Comment by jinyang1994** [comment]
My simple example is here [Example](https://github.com/jinyang1994/example)

**Comment by jinyang1994** [comment]
It still doesn't solve my problem

**Comment by o4dev** [comment]
Why is this closed? Was anybody able to solve this?
