### ISSUE TITLE
blob links seem applied to the dom after js execution occasionally

### ISSUE THREAD

**Issue by wusiquan** [webpack-contrib/style-loader#352]
hi, I found the sentence in README

> when style loader is used with { options: { sourceMap: true } } option, the CSS modules will be generated as Blobs...

then I enabled the `soruceMap` option, see the page in the latest Chrome(70.0.3538.110) when **developing**.

and js seems executed before the css applied to the dom `occasionally`, for instance, the page I write used `swiper` plugin, which calculate the `slideSize` would get the wrong size `occasionally` 
is it a chrome's bug? or the blob related problem?

**Comment by evilebottnawi** [comment]
@wusiquan It can happen, you need load styles first when init swiper, use `import().then().catch()` for this. Looks `swiper` use `height` or `width` styles to calculate something

**Comment by wusiquan** [comment]
@evilebottnawi Thank you for your replying. 
I tried the `import()` way, `Promise('./index.scss', './swiper.scss').all(() => new Swiper(...))`
but this time the `swiper` *always* calculate the wrong value...

After digging into the waterfall, I found the parse blob stylesheet section was hehind the execution
![waterfall](https://raw.githubusercontent.com/wusiquan/wusiquan.github.io/master/watherfall1-style-loader-issue352.png)

so, for temporoly solution, set the sourceMap option to false or init swiper in window.onload callback function, which let swiper plugin calculate the right value internally

**Comment by wusiquan** [comment]
ok, please wait a while...I'll paste the repo link url

**Comment by wusiquan** [comment]
all right, the [repo](https://github.com/wusiquan/style-loader-issue-352) has been created

**Comment by evilebottnawi** [comment]
@wusiquan thanks!

**Comment by wusiquan** [comment]
@evilebottnawi the same thanks to you. Hope it can help you reproduct.

**Comment by rafaeldeoliveira** [comment]
this also happens in a project I'm working on

**Comment by flut1** [comment]
I encountered this as well in a VueJS project. After vue has rendered the page (in the `mounted()` hook) I can see that the `<style>` tags have been inserted with blobs, but the styles are not applied to the page yet. If I wait a single tick (`setTimeout` of 0) the styles have been applied

Setting `sourceMap` to false also resolves the issue for me

**Comment by 4WakeStudio** [comment]
Same problem here :/.
Any better fix found?

**Comment by flut1** [comment]
@4WakeStudio  Not a real fix but a workaround. We now have a little util function that returns a Promise when all stylesheets have loaded. You can use that to delay code that depends on the styles being applied.

```
waitForStyleSheetsLoaded(document).then(() => { /* styles are now loaded */ });
```

See: 
https://github.com/riccoarntz/vue-skeleton/blob/5c6e393abeb352df3c9f17b3a8a6ba411d80559e/src/util/waitForStyleSheetsLoaded.ts

**Comment by ke1vin1993** [comment]
Not occasionally. Only safari works correctly with blob links now

**Comment by vlasenko** [comment]
@evilebottnawi Thanks, could you also publish `style-loader` with the #383 fix merged?

**Comment by evilebottnawi** [comment]
@vlasenko we have some tasks for new release, so just wait, i think we can do release on next week
