### ISSUE TITLE
[Question] what's the meaning of the double ! in style-loader source code? 

### ISSUE THREAD

**Issue by njleonzhang** [webpack-contrib/style-loader#354]
I know I should not ask question here, but I have asked this question in [stackoverflow](https://stackoverflow.com/questions/53611811/whats-the-meaning-of-the-double-in-style-loader-source-code), but none answer it till now. Would you please take a look to the [question](https://stackoverflow.com/questions/53611811/whats-the-meaning-of-the-double-in-style-loader-source-code), thanks very much.

**Comment by evilebottnawi** [comment]
You can read information here (https://webpack.js.org/configuration/module/#rule-enforce), better create these issues in webpack docs repo, thanks

**Comment by njleonzhang** [comment]
@evilebottnawi tnx very much for your response
