### ISSUE TITLE
Not working in Chrome 71 Headless mode

### ISSUE THREAD

**Issue by redeyes2015** [webpack-contrib/style-loader#355]
**Do you want to request a *feature* or report a *bug*?**

A bug ... of Chrome 71 Headless mode.

**What is the current behavior?**

The default behavior in Chrome would use blob URLs to inject styles,
and thus not working in Chrome 71 headless mode.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I just want to leave a notice here, hoping to help others who also use Chrome headless mode
with style-loader.

A few work-arounds are possible:

1. `singleton: true` : easiest change; however, in my situation, huge style sets seem to prevent the
    scripts from executing properly.
2. Remove source maps : notice that one must disable source maps from "upstream",
    e.g. `css-loader` and `less-loader` ; having `{ loader: 'style-loader', options: {sourceMap: false} }`
    alone is not enough.
3. Replace style-loader ... maybe with `style-loader/url + file-loader`

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

Related: https://github.com/GoogleChrome/puppeteer/issues/3463

**Comment by evilebottnawi** [comment]
@redeyes2015 just add `blob` polyfill, maybe we can auto detect and load polyfill when it is necessary

**Comment by renchap** [comment]
This is a known bug in Chrome 71 (https://bugs.chromium.org/p/chromium/issues/detail?id=902918&desc=2), I am not sure it is worth it to include a workaround in `style-loader`.

**Comment by evilebottnawi** [comment]
@redeyes2015 thanks for link

**Comment by evilebottnawi** [comment]
Closed due bug in chrome, we can't do something on our side, anyway if you have idea(s), PR welcome
