### ISSUE TITLE
Css included in bundles js files instead of in style tag

### ISSUE THREAD

**Issue by modestotech** [webpack-contrib/style-loader#356]
**What is the current behavior?**
Instead of getting styles in a style tag, I get all styles included in the bundles js file. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Production works good, I get the minified css as expected, but style-loader has no effect. Even if I remove style-loader, I still get the css into the bundled `app.js` file. 

```js
        test: /\.(sa|sc|c)ss$/,
        use: [
          isInProductionMode ? MiniCssExtractPlugin.loader : 'style-loader',
          {
            loader: 'css-loader',
            options: {
              importLoaders: 1,
            },
          },
          {
            loader: 'postcss-loader',
            options: {
              config: {
                ctx: {
                  isInProductionMode, // for including cssnano only in production builds
                },
              },
            },
          },
          'sass-loader',
        ],

```

**What is the expected behavior?**
I expect style-loader to put all css in a style tag.

**Comment by modestotech** [comment]
> @modestotech please create minimum reproducible test repo

[Here](https://github.com/modestotech/css-test) you are. Run with buildTest to build and serve the content on a local server. The css gets included in the bundled js file.

**Comment by evilebottnawi** [comment]
@modestotech expected, what you want? `css-loader` transpile `css` into `js` modules and `style-loader` insert this in `style` tag

**Comment by modestotech** [comment]
> @modestotech expected, what you want? `css-loader` transpile `css` into `js` module(s) and `style-loader` insert this in `style` tag

I expect the css to be injected in a style tag in `index.html`. The screenshot below shows that there is no style tag. 

![image](https://user-images.githubusercontent.com/31730051/50288687-e5cb6c00-0466-11e9-8170-24af5469ce86.png)

Have I misunderstood the functioning?

**Comment by evilebottnawi** [comment]
@modestotech it is include `style` tag in runtime time (when `app.[hash].js`) was loader `style` tag should be appear

**Comment by modestotech** [comment]
> @modestotech it is include `style` tag in runtime time (when `app.[hash].js` was loaded `style` tag should be appear)

I don't get it to appear. See [this](https://streamable.com/ffvf7) video.

**Comment by modestotech** [comment]
Oh, my bad :) Thanks
