### ISSUE TITLE
`npm i style-loader` does not work

### ISSUE THREAD

**Issue by stoneshower** [webpack-contrib/style-loader#357]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`npm i style-loader` does not work and I cannot install style-loader

Log:
60 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "style-loader" "--save"
61 verbose node v10.6.0
62 verbose npm  v6.1.0
63 error Cannot read property 'match' of undefined
64 verbose exit [ 1, true ]

**Comment by evilebottnawi** [comment]
@stoneshower looks problem on `npm` side, we can't help here, you can try update `npm` or remove caches (`npm cache clean`)
