### ISSUE TITLE
options.insertTo (function or selector) is used before React component is mounted

### ISSUE THREAD

**Issue by jimousse** [webpack-contrib/style-loader#361]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
I'm using React and I have a component that has an id `test`.
I'm using the style-loader this way:
```
{
  loader: 'style-loader',
    options: {
       insertInto: () => {
         return document.querySelector('#test');
       },
    },
}
```
When `insertInto` is run, my react component is not mounted yet, therefore `document.querySelector('#test')` returns always null.

**What is the expected behavior?**
I'd like `insertInto` to be executed when React inserts the nodes into the DOM.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
`react`: 16.0.0 
`webpack`: 3.11.0
`style-loader`: 0.23.1
`node`: 8.5.0

**Comment by evilebottnawi** [comment]
@jimousse out of scope loader, you can use `import('style.css').then(() => {})` when you need include styles

**Comment by evilebottnawi** [comment]
Answer above, also we have `usable` api for this case
