### ISSUE TITLE
options.transform is a string, not a function

### ISSUE THREAD

**Issue by jordanbtucker** [webpack-contrib/style-loader#369]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

Error `options.transform should be a string` is thrown when `options.transform` is a function.

**If the current behavior is a bug, please provide the steps to reproduce.**

webpack.config.js

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          {
            loader: 'style-loader',
            options: { transform: css => css.replace('.a', '.b') }
          },
          { loader: 'css-loader' } 
        ]
      }
    ]
  }
}
```

**What is the expected behavior?**

The [documentation](https://github.com/webpack-contrib/style-loader/blob/v0.23.1/README.md#options) states that `options.transform` is a `Function`, however it appears that it is [actually a `string`](https://github.com/webpack-contrib/style-loader/blob/v0.23.1/README.md#transform) representing the path to a module that exports a function.

Either `options.transform` should actually accept a function, or the documentation should be updated to reflect that `options.tranform` is really a string. As it stands, the documentation contradicts itself.

**Comment by evilebottnawi** [comment]
Yep, it is bug

**Comment by evilebottnawi** [comment]
option transform was removed without replacement
