### ISSUE TITLE
reduce the difference in api between normal and lazy imports

### ISSUE THREAD

**Issue by midsbie** [webpack-contrib/style-loader#379]
* Operating System: Ubuntu Linux latest LTS
* Node Version: 11.15
* NPM Version: 6.7.0 (yarn 1.13.0)
* webpack Version: 4.31.0
* style-loader Version: 0.23.1

### Expected Behavior
Enabling `style-loader/useable` loader whilst using CSS modules results in CSS modules not working.  

### Actual Behavior
Whenever `style-loader/useable` is used, CSS modules are ignored as if `css-loader:modules = false`. Reverting to the `style-loader` loader, causes CSS modules to work once again.

### Code
```js
        {
          test: /\.scss$/,
          use: [
            {
              loader: "style-loader/useable",
              options: {
                insertInto: () => document.querySelector(TARGET_SELECTOR),
              },
            },
            {
              loader: "css-loader",
              options: {
                modules: true,
                sourceMap: true,
                importLoaders: 2,
                localIdentName: "[md5:hash:hex:8]",
              },
            },
            { loader: "postcss-loader" },
            { loader: "sass-loader" },
          ],
        },
```

### How Do We Reproduce?
Stated in "Actual Behavior".

### Additional Comments
I took a look at the code and it would seem there is a difference in how the content export is done.  Specifically, `style-loader` has:

```js
		"if(content.locals) module.exports = content.locals;",
```

whereas `style-loader/useable` does:

```js
		"if(content.locals) exports.locals = content.locals;",
```

The latter form exports to the `locals` attribute. Could this be the reason? If so, is the reason for exporting as `locals` a measure to avoid collision with `use`/`unuse` and `ref`/`unref`? How can we fix this such that changing between the `style-loader/useable` and `style-loader` loaders doesn't cause breakage?

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by evilebottnawi** [comment]
Looks like a bug

**Comment by saculbr** [comment]
I created a minimal reproducible test repo https://github.com/saculbr/useable-export-minimal-repo

and, **when using modules** all class names are exported inside a *locals* variable

this behavior is not documented

![DeepinScreenshot_select-area_20190729183816](https://user-images.githubusercontent.com/4311885/62084605-14e16180-b230-11e9-969e-ce6e1f57d0fd.png)

![DeepinScreenshot_select-area_20190729184345](https://user-images.githubusercontent.com/4311885/62084938-d1d3be00-b230-11e9-99d3-c389d645d159.png)

**Comment by miguel-guedes** [comment]
Thanks for the repro, @saculbr -- been lacking the time! :+1:

**Comment by evilebottnawi** [comment]
It is not bug, expected, because `css` modules can contains `ref`/`unref`/`unser`/`use` class name we need export this in `locals`, we need documented this

**Comment by evilebottnawi** [comment]
Problem:
- normal usage exports locals in imported object
- lazy usage exports locals under `locals` property of imported object

We need reduce change between this.
