### ISSUE TITLE
I need help 

### ISSUE THREAD

**Issue by HighWarmModel** [webpack-contrib/style-loader#380]
In the development environment, I introduced the CSS file into the JS file, but it was a style rendered by js, which led to incorrect calculation of dom.
eg:[https://github.com/seafronthu/webpack4-multi-page](url)
In index.js, `document.querySelector('.ljb').offsetTop //  It's not the right value before CSS rendering`
How can I solve this problem?

**Comment by evilebottnawi** [comment]
Please open new issue with issue template and step to reproduce, thanks
