### ISSUE TITLE
Replace original Style link to blob one

### ISSUE THREAD

**Issue by weilinzung** [webpack-contrib/style-loader#381]
### Feature Proposal

We have a Jekyll project, during local development that `main.css` would be missing(404) because Webpack has not generated the final CSS file. Would be nice if style-loader could replace the original style link to the blob one.

### Feature Use Case

`<link id="main-style" rel="stylesheet" href="/css/main-bundle.css">` 404-> during local development

Just give an new option to replace or overwrite the original link to this:

`<link type="text/css" rel="stylesheet" href="blob:http://localhost:3000/00949e64-20a8-4b32-9fe9-f2fff551bc4d">`

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/mini-css-extract-plugin

**Comment by weilinzung** [comment]
@evilebottnawi it is quite slow if doing that on local development.

**Comment by evilebottnawi** [comment]
@weilinzung it is impossible without plugins, we can fix problem with perf
