### ISSUE TITLE
usable and hmr issues

### ISSUE THREAD

**Issue by jonasi** [webpack-contrib/style-loader#41]
I'm seeing an issue with style-loader usable and HMR when the usable `refs` count is > 1.  In this scenario, when a style module is updated the style disappears from the DOM but is never reinserted/updated.  In the case where `refs` === 1, everything works as expected.

Looking at the code, I'm a little confused by how the `refs` in `usable.js` interacts with the `refs` count inside `addStyles`.  But from a little debugging, it looks like the  `dispose` callback in `usable.js` is getting called but `exports.ref` is not because refs > 0.

**Comment by syranide** [comment]
+1 seeing this as well

**Comment by SpaceK33z** [comment]
Do you still have these issues?

**Comment by syranide** [comment]
Just commenting to say that "I don't know" and I'm not using Webpack 2 yet so it's not trivial to check.

**Comment by michael-ciniawsky** [comment]
@jonasi @syranide Sry to come again with the standard blub blub 😛 Is this still happening? webpack 2 ? latest `style-loader`? related to #122 ?

**Comment by syranide** [comment]
@michael-ciniawsky Sorry, still haven't had time to upgrade to webpack 2 🙈

**Comment by evilebottnawi** [comment]
@syranide can your provide minimum reproducible test repo, just confirm bug exists?
