### ISSUE TITLE
Using injectType linkTag with webpack leads to url being an esModule

### ISSUE THREAD

**Issue by 4iAmAve** [webpack-contrib/style-loader#428]
- Operating System: Windows 10/Ubuntu 19/MacOS latest
- Node Version: latest
- NPM Version: latest
- webpack Version: 4.41
- style-loader Version: 1.0.0

### Expected Behavior

The injected link tag should reference the correct link URL.

### Actual Behavior

The passed `url` parameter into the link tag function is an esModule (for whatever reason) as follows:

```json
{
  "default": "//localhost:4001/main.css"
}
``` 

Hence the appended `<link />` child looks like this:

```html
<link rel="stylesheet" href="[object Module]">
```

No matter whether we use `import './main.css'` or `require('./main.css');` in our component code.
Even `import styles from './main.css'` does not help. 

### Code

```js
    {
        test: /\.css$/,
        use: [
          {
            loader: 'style-loader',
            options: {
              injectType: 'linkTag'
            }
          },
          {
            loader: 'file-loader',
            options: {
              name: 'main.css',
            },
          },
        ]
      },
```

**Comment by evilebottnawi** [comment]
Thanks for issue :+1:

**Comment by 4iAmAve** [comment]
Shall I provide a PR?

**Comment by evilebottnawi** [comment]
@4iAmAve no need, i already WIP on this :+1:

**Comment by 4iAmAve** [comment]
@evilebottnawi 

Thanks a lot. That went fast. :)
