### ISSUE TITLE
Build not ok with injectType of style-loader

### ISSUE THREAD

**Issue by Acksop** [webpack-contrib/style-loader#430]
- Operating System: Linux Mint 19.2
- Node Version: v8.10.0
- NPM Version: 3.5.2
- webpack Version: 4.41.2
- style-loader Version: ^1.0.1

### Expected Behavior

npm run Build -->OK!

### Actual Behavior

https://gist.github.com/Acksop/f5c39cb60d416b5660f3ea8df542c60c

### Code
`webpack.config.js`
https://gist.github.com/Acksop/9ba4bfc40ab3996d95cd4b9d3ae1546b

```js
`src/entry-point.js`
//-- Import CSS Styles
import inlinestyles from './css/inline.css';
import lazystyles from './css/main.lazy.css';
import linkstyles from './css/plugins.link.css';

console.info('Saluto!');
```

**Comment by evilebottnawi** [comment]
`linkTag` should be used with `file-loader`, please read docs, thanks

**Comment by Acksop** [comment]
thanks, i'm a newbie with npm ... I just begin to understand how it works. so thank for your help !

**Comment by evolverine** [comment]
Sure, but this way one can't process the urls inside the css, no? Or am I missing something?

**Comment by evolverine** [comment]
Found a solution to my issue, using [extract-loader](https://webpack.js.org/loaders/extract-loader/)

```javascript
     {
        test: /\.css$/i,
        use: [{ loader: "style-loader", options: { injectType: "linkTag" } },
        "file-loader",
        "extract-loader",
        "css-loader"
       ],
    },
```
