### ISSUE TITLE
feat: named exports

### ISSUE THREAD

**Issue by TrySound** [webpack-contrib/style-loader#431]
**Do you want to request a *feature* or report a *bug*?**

Feature 

**What is the current behavior?**

**What is the expected behavior?**

Would be great to have a named exports mode which can help to verify class existing by new webpack feature. Not quite sure it works now.  But in theory it can fix lots of is issues.

**Comment by evilebottnawi** [comment]
Better implement that on `style-loader` side

**Comment by evilebottnawi** [comment]
You can use `import * as style from './myStyle.css';` with `styleTag` and `lazyStyleTag` and all works fine, closing
