### ISSUE TITLE
v1.1.0 broke loading styles 

### ISSUE THREAD

**Issue by crobinson42** [webpack-contrib/style-loader#446]
#445 says v1.1.0 broke "Ant Design"... well it actually broke bundling any css/scss in the webpack build process.

No css is bundled with the below configs for v1.1.0.

**Rolling back to v1.0.2 fixes this issue.**

```
...
{
        test: /\.(css|scss)$/,
        use: [
          {
            loader: 'style-loader',
          },
          {
            loader: 'css-loader',
          },
          {
            loader: 'resolve-url-loader',
          },
          {
            loader: 'sass-loader',
            options: {
              sourceMap: true,
            },
          },
        ],
      },
...
```

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by evilebottnawi** [comment]
Should be solved https://github.com/webpack-contrib/style-loader/releases/tag/v1.1.2, please leave feedback
