### ISSUE TITLE
v.1.1.1 throw error when accessing the page

### ISSUE THREAD

**Issue by yyzclyang** [webpack-contrib/style-loader#447]
- Operating System: macOS 10.14.6
- Node Version: 12.14.0
- NPM Version: 6.13.4 (yarn 1.19.1)
- webpack Version: 4.41.3
- style-loader Version: 1.1.1

### Expected Behavior
`style-loader` operating normally

### Actual Behavior

After I upgraded from 1.0.2 to 1.1.1, webpack compiles, but I get an error (`Uncaught RangeError: Invalid array length`) when accessing the webpage.When I downgrade 1.0.2, it's fine.

### Code

```js
// webpack.config.js
// If your code blocks are over 20 lines, please paste a link to a gist
// (https://gist.github.com).
{
        test: /\.s?css$/,
        use: [
          "style-loader",
          MiniCssExtractPlugin.loader,
          "css-loader",
          "postcss-loader",
          "sass-loader"
        ]
}
```

### How Do We Reproduce?

Stated in "Actual Behavior".

**Comment by saranchandru** [comment]
The same issue is happening with the 1.1.0 version as well.

**Comment by syberon** [comment]
Yes, i confirm this too. After updating to 1.1.1 from 1.0.2 i get the same error.

**Comment by evilebottnawi** [comment]
Somebody can create reproducible test repo?

**Comment by yyzclyang** [comment]
> Somebody can create reproducible test repo?

here https://github.com/yyzclyang/style-loader-test-repo

**Comment by evilebottnawi** [comment]
Problem in configuration, you should not use MiniCssExtractPlugin.loader and `style-loader` together, please fix it using:
```js
{
        test: /\.scss$/,
        use: [
          isDev ? "style-loader" : MiniCssExtractPlugin.loader,
          "css-loader",
          "postcss-loader",
          "sass-loader"
        ]
},
```

**Comment by evilebottnawi** [comment]
I will fix it for current version to avoid breaking change, but it doesn't work for next version

**Comment by yyzclyang** [comment]
> I will fix it for current version to avoid breaking change, but it doesn't work for next version

thank you !
