### ISSUE TITLE
Enhancement:  Allow customization of request URI to differ from source file's URI

### ISSUE THREAD

**Issue by dwoldrich** [webpack-contrib/style-loader#45]
I have the following loader expression:
    style/url?limit=0!file?name=css/[name].css!sass

If, for example, I have a hello.sass file, it is compiled and written as a plain text/css file to css/hello.css.  Finally, the style/url part yields the following javascript that I want which dynamically loads the css file:

```
/* 6 */
/***/ function(module, exports, __webpack_require__) {

    module.exports = __webpack_require__.p + "css/hello.css"

/***/ },
/* 7 */
/***/ function(module, exports, __webpack_require__) {

    /*
        MIT License http://www.opensource.org/licenses/mit-license.php
        Author Tobias Koppers @sokra
    */
    module.exports = function addStyleUrl(cssUrl) {
        if(false) {
            if(typeof document !== "object") throw new Error("The style-loader cannot be used in a non-browser environment");
        }
        var styleElement = document.createElement("link");
        styleElement.rel = "stylesheet";
        styleElement.type = "text/css";
        styleElement.href = cssUrl;
        var head = document.getElementsByTagName("head")[0];
        head.appendChild(styleElement);
        if(false) {
            return function(cssUrl) {
                if(typeof cssUrl === "string") {
                    styleElement.href = cssUrl;
                } else {
                    head.removeChild(styleElement);
                }
            };
        }
    }

/***/ }
```

_I would like more control over module 6_.  Specifically, I'd like to be able to add the [hash] for the hello.css as a query string parameter to the end of the "css/hello.css" URI.  Generating the javascript with the [hash] in the URI's query string will allow me to serve my .css with a never-expires cache header and maximize the user's browser cache.

Ideally, module 6 would look something like this:

```
/* 6 */
/***/ function(module, exports, __webpack_require__) {

    module.exports = __webpack_require__.p + "css/hello.css?09341d1ff67217aae4777cf9222efe5f"

/***/ },
```

I tried modifying name on the style/url, but this did not seem to have any effect:
    style/url?limit=0&name=css/[name].css?[hash]!file?name=css/[name].css!sass

Is there a way that I can tailor the URI generated for the .css URL request?  If not, may I request that as an enhancement for style-loader?  Thanks!

**Comment by sokra** [comment]
`style/url?limit=0!file?name=css/[name].css?[hash]!sass`

---


but I recommend using `style!css!sass` instead and use the `extract-text-plugin` to generate a separate css file.

**Comment by dwoldrich** [comment]
Hi @sokra,

Thanks for responding.  I tried your suggested loader expression, and I get the following error on the gulp-webpack command line:

Error: Path doesn't exist '/volumes/DCW/project/css/hello.css?3cbfb6b70597d49d816808fdb536ab28'

The hello.css does exist at that location, but with the question mark and hash included, the file is not found.

Here's what my webpackArgs look like with your suggested expression included:

```
var webpackArgs = {
    module: {
        loaders: [
            {
                test: /\.scss$/,
                loader: "style/url?limit=0!file?name=css/[name].css?[hash]!sass?outputStyle=" + (isProductionMode ? "compressed" : "expanded") + 
                    "&includePaths[]=" +
                    (path.resolve(__dirname, "./bower_components")) +
                    "&includePaths[]=" +
                    (path.resolve(__dirname, "./node_modules")) 
            }
        ]
    },
    output: {
        filename: "js/[name].js",
    }
};
```

I'm not sure what an ideal fix for this would be, but I had a thought for a quick fix:  the code in webpack that is trying and failing to resolve the "hello.css?3cbfb6b70597d49d816808fdb536ab28" file on the filesystem could always strip query string and hash parameters from the file URI before trying to resolve the file.

Cheers,
Dave

**Comment by michael-ciniawsky** [comment]
@dwoldrich Please use `extract-text-webpack-plugin` (recommended) instead. Mind sending a quick PR with the `?[hash]` proposal for futher discussion 😛  ?
