### ISSUE TITLE
Question about insertAt in options of style-loader

### ISSUE THREAD

**Issue by Kasensil** [webpack-contrib/style-loader#454]
Thank you for reading my question! I am a beginner, in the process of learning encountered a little problem I hope you can explain!Why can't I implement this using '**insertAt**' as the webpack documentation says instead of inserting my style at the top of the 'head' using the function in the project(as you wrote in the documentation)? In the webpack documentation, 'insertAt' is an option parameter, but why is it not prompted when it is used?As is shown in the picture....
![TIM截图20200107225626](https://user-images.githubusercontent.com/53079487/71904724-a373ea80-31a1-11ea-96f1-9f0b8e0febbf.png)

**Comment by anikethsaha** [comment]
Its `insert` , not `insertAt`.
ref this https://github.com/webpack-contrib/style-loader#insert

**Comment by Kasensil** [comment]
> Its `insert` , not `insertAt`.
> ref this https://github.com/webpack-contrib/style-loader#insert

But I don't want to use **insert** to change the position of the insert tag but their position in the 'head' tag, so the default is bottom and I want to change it to top

**Comment by Kasensil** [comment]
> Its `insert` , not `insertAt`.
> ref this https://github.com/webpack-contrib/style-loader#insert
 So is **insert** the same thing as **insertAt**?

**Comment by anikethsaha** [comment]
> So is insert the same thing as insertAt?

I am not sure where you saw insertAt.? can you share the link where you saw that ?

as far as `insert` is a concern, it will change the position of inserting the tag as per the option passed.

**Comment by Kasensil** [comment]
> I am not sure where you saw insertAt.? can you share the link where you saw that ?
> 
> as far as `insert` is a concern, it will change the position of inserting the tag as per the option passed.
In a Chinese document... Is this out of date?[https://www.webpackjs.com/loaders/style-loader/#insertat](url)

**Comment by anikethsaha** [comment]
> In a Chinese document... Is this out of date?
> https://www.webpackjs.com/loaders/style-loader/#insertat

strange !!
Yup, thats wrong/outdate
Also, if you want to refer the webpack's Chinese docs , refer this one https://webpack.docschina.org/

**Comment by Kasensil** [comment]
[https://www.webpackjs.com/loaders/style-loader/#insertat](url)
In a Chinese document... Is this out of date?

**Comment by anikethsaha** [comment]
> In a Chinese document... Is this out of date?

Yess. They didnt update the changes.

**Comment by Kasensil** [comment]
> > In a Chinese document... Is this out of date?
> 
> Yess. They didnt update the changes.

Thank you very much! So insertAt doesn't work anymore, does it?

**Comment by anikethsaha** [comment]
no, if you are on latest version of `style-loader` it wont work. use `insert`

**Comment by Kasensil** [comment]
> no, if you are on latest version of `style-loader` it wont work. use `insert`

Very grateful! Thank you so much!

**Comment by anikethsaha** [comment]
Glad to help 😃

**Comment by anikethsaha** [comment]
you can close this issue

**Comment by Kasensil** [comment]
> you can close this issue

ok😄

**Comment by Kasensil** [comment]
> you can close this issue

ok😄
