### ISSUE TITLE
After v0.23.1, it is not working correctly with BroswerSync Style Injection 

### ISSUE THREAD

**Issue by weilinzung** [webpack-contrib/style-loader#455]
Issues are so 🔥

With older version `v0.23.1`, default with Webpack would create `blob` link type style injection. Which works great with `BroswerSync` auto-style injection without FULL-PAGE reload. With the latest `style-loader` version, `BroswerSync` would full reload the page when CSS is updated.

- Operating System:
- Node Version: v11.13.0
- NPM Version: 6.7.0
- webpack Version: 4.41.5
- style-loader Version: v1.1.2

### Expected Behavior

Adding back `blob` link type which would help for using BroswerSync that without full page reload, also for local development would be faster.

### Actual Behavior

No option for `blob` link type option.

**The new option `linkTag` is required to extract the style into CSS file first which should NOT be necessary because of just adding an extra step for local development. So can we have the `blob` link type option back?**

**Comment by evilebottnawi** [comment]
Please open issue in `BroswerSync`
