### ISSUE TITLE
Invalid placement of "CSS @import rules" when injectType is singletonStyleTag.

### ISSUE THREAD

**Issue by amid2887** [webpack-contrib/style-loader#457]
- Node Version: 10.17.0
- NPM Version: 6.11.3
- webpack Version: 4.41.5
- style-loader Version: 1.1.3

### Expected Behavior

CSS `@import` rule should be placed at the very top of CSS, before any rules.

### Actual Behavior

CSS `@import` rule is placed between styles.

### How Do We Reproduce

[Playground with example](https://codesandbox.io/s/objective-brook-nqzsn).

You have a few css files.
```css
/* style1.css */
.someStyles { ... }
```
```css
/* style2.css */
@import url(external.css);
.someStyles2 { ... }
```
```css
/* external.css */
.someStyles3 { ... }
```

You have a webpack config with style-loader options set to `injectType: singletonStyleTag`.
```js
// webpack.config.js
module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/i,
        use: [
          {
            loader: 'style-loader',
            options: {
              injectType: 'singletonStyleTag'
            }
          },
          'css-loader'
        ]
      }
    ]
  }
};
```

You import these css files into your app.
```js
// index.js
import 'style1.css';
import 'style2.css';
```

You got this in the browser (**`@import` rule has invalid placement.**).
```html
<style>
.someStyles  { ... }
@import url(external.css);
.someStyles2 { ... }
</style>
```

>The `@import` CSS at-rule is used to import style rules from other style sheets. These rules must precede all other types of rules, except `@charset` rules;
> [@import - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@import)

There is no issue when you have `styleTag` as injectType value.
```html
<style>.someStyles  { ... }</style>
<style>@import url(external.css);</style>
<style>.someStyles2 { ... }</style>
```

Also `mini-css-extract-plugin` works fine with that kind of imports and looks like it has some [sorting for the @import rules](https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L549).
```css
@import url(external.css);
.someStyles  { ... }
.someStyles2 { ... }
```

[Playground with example](https://codesandbox.io/s/objective-brook-nqzsn).

**Comment by evilebottnawi** [comment]
We prepare next major release and will remove `singleton` support so better start to migrate on `styleTag`

**Comment by amid2887** [comment]
Okaaay...
