### ISSUE TITLE
esModule option behaviour 

### ISSUE THREAD

**Issue by krail** [webpack-contrib/style-loader#459]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- style-loader Version:

### Expected Behavior

When `esModule` option set `true` all css imports has to have module syntax in bundle.

### Actual Behavior

Only one import has module syntax. Other has common-js syntax.

### Code

```js
// webpack.config.js
{ loader: 'style-loader', options: { esModule: true } },
```

```js
// bundle.js

// one import with module syntax
/* harmony import */ var _node_modules_style_loader_dist_runtime_injectStylesIntoStyleTag_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../../../../../../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js */ "./node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js");

// others imports in same bundle
var api = __webpack_require__(/*! ../../../../../../../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js */ "./node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js");
```

Looks like this code break it:
https://github.com/webpack-contrib/style-loader/blob/2756e03e7caf71f4d2800efa906d90ff34915bca/src/index.js#L28

**Comment by evilebottnawi** [comment]
Yes, it is expected and it will be breaking change in next version

**Comment by Liar0320** [comment]
Is it working properly now。
I also have the same problem now。
