### ISSUE TITLE
lazyStyleTag breaks HMR

### ISSUE THREAD

**Issue by rhendric** [webpack-contrib/style-loader#467]
- Operating System: Arch Linux
- Node Version: v13.13.0
- NPM Version: 6.14.4
- webpack Version: 4.43.0
- style-loader Version: 1.2.0

### Expected Behavior

When a CSS stylesheet is loaded via `style-loader` and `injectType: 'lazyStyleTag'`, and HMR is enabled, updating the stylesheet file should result in the style being hot replaced in the browser, regardless of the current state of the `use`/`unuse` ref count. (If the style is unused at the time, the changes should be visible when the style is next used.)

### Actual Behavior

If the style is in use, then the change is visible, but as soon as the style is unused and then used again (or if the style is unused at the time of the HMR event), then the style reverts to its original value until the page is cold reloaded.

### Code + How Do We Reproduce?

Check out https://github.com/rhendric/upgraded-spork for a minimal reproduction. Clicking the button toggles the stylesheet on and off. Edit the background color in `src/index.css` and then click the button a few times to reproduce the issue.

**Comment by evilebottnawi** [comment]
Thanks for the issue, it is bug, WIP

**Comment by rhendric** [comment]
Thank you for a fast fix and release! 1.2.1 works for me.
