### ISSUE TITLE
Identify StyleTag via an attribute

### ISSUE THREAD

**Issue by tooltonix** [webpack-contrib/style-loader#470]
Hello,

I currently have the problem that we use two CSS files:
the first one is for the mobile version and the second one for the desktop version, which uses a media query. Both files get different media queries, so I have to identify them during the development process in Webpack. So I used a very old [fork ](https://github.com/bukuta/style-loader#attrs) from the StyleLoader, which could pass the name of the CSS file in an [attribute](https://github.com/bukuta/style-loader#attrs) to the style tag for identification:

`options: { attrs: { id: 'id' , 'data-from': '[path][name].[ext]'} }`

Is there a similar possibility with the current version of the StyleLoader? Currently I abuse the possibility to add a nonce attribute to the style tags.

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack-contrib/style-loader/issues/216, please don't ignore the issue template
