### ISSUE TITLE
”insertAt: top“  throws an exception when packaging

### ISSUE THREAD

**Issue by Sympath** [webpack-contrib/style-loader#472]
```
options: {
		insertAt: 'top'
	}
```
When learning webpack, If I want to put the compiled CSS at the top of the page, like the document configuration, it will fail to pack
```
options has an unknown property 'insertAt'. These properties are valid:
   object { injectType?, attributes?, insert?, base?, esModule? }
```
But I have the same configuration as the official website, so I am confused, is there any solution?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please read docs - https://github.com/webpack-contrib/style-loader#insert
