### ISSUE TITLE
Incorrect handling of esModule option

### ISSUE THREAD

**Issue by dangreen** [webpack-contrib/style-loader#475]
> https://github.com/webpack-contrib/style-loader/blob/master/src/index.js#L30

```js
delete options.esModule;
```

> https://github.com/webpack/loader-utils/blob/master/lib/getOptions.js

`loaderUtils.getOptions` doesn't copy options, just returns original object (`loaderContext.query`).

`esModule` option will be removed after first loader call, so farther calls will produce commonjs exports.

It breaks `require` imports: 

```js
require('./default.lazyModule.scss').default // undefined
```

Reproduction of this bug can be unstable, I think it caused by webpack's internal optimizations.

**Comment by evilebottnawi** [comment]
Please use the issue template in future

**Comment by dangreen** [comment]
I think I can make PR with fix.

**Comment by evilebottnawi** [comment]
Fixed in the master

**Comment by dangreen** [comment]
@evilebottnawi How soon release with this fix will published?

**Comment by evilebottnawi** [comment]
I hope near future, we want to do mini-css-extract-plugin and style-loader releases together (set `esModule: true`), otherwise it can create problems for developers

**Comment by dangreen** [comment]
👌
