### ISSUE TITLE
Document relationship to css-loader

### ISSUE THREAD

**Issue by scottdotjs** [webpack-contrib/style-loader#477]
Documentation Is:

- [X] Missing
- [ ] Needed
- [X] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

The documentation says "It's recommended to combine mini-css-extract-plugin with the css-loader" without any further explanation. Why is it recommended, what happens if you do, what happens if you don't?

### Your Proposal for Changes

Please add an explanation. Thank you!

Note: I opened an identical issue for [the same comment in the mini-css-extract-plugin docs](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/494).

**Comment by evilebottnawi** [comment]
> Why is it recommended, what happens if you do, what happens if you don't?

Because you can use any custom loader, but we recommended to use `mini-css-extract-plugin`, what is unclear?

**Comment by evilebottnawi** [comment]
> what happens if you don't

I don't know, because I don't know what loader you will use

**Comment by scottdotjs** [comment]
> > Why is it recommended, what happens if you do, what happens if you don't?
> 
> Because you can use any custom loader, but we recommended to use `mini-css-extract-plugin`, what is unclear?

I'm not sure how to answer that without repeating my original question, which you quote. _Why_ do you recommend it? What benefit does it bring over other loaders? For someone that's trying to learn the Webpack ecosystem, the documentation creates questions that are difficult to answer, instead of providing context that allows decisions to be made.

>  > what happens if you don't
> 
> I don't know, because I don't know what loader you will use

Neither do I, which is the problem. The fact that you're recommending using a particular plugin suggests that there are advantages to using it, or possibly disadvantages to not using it - but what these may be isn't specified.

Thank you.

**Comment by evilebottnawi** [comment]
@scottdotjs I am afraid that this is actually difficult to explain in a few words and will require a lot of information - CJS/ES modules/CSS/internal loaders works/inject styles on DOM, extracting and splitting modules, I'll just delete this line so that there are no unnecessary questions. If you start to work with webpack style-loader/mini-css-extract-plugin + css-loader is the best choice

**Comment by evilebottnawi** [comment]
You can replace css-loader on own implementation, but it is not required in 99,99% cases, so if you want to implement an own loader instead css-loader, then you already know very well

**Comment by scottdotjs** [comment]
OK - thank you. :)
