### ISSUE TITLE
preserve toString() from css-loader

### ISSUE THREAD

**Issue by JasonWoof** [webpack-contrib/style-loader#481]
### Feature Proposal

Normally I use both css-loader and style-loader as is generally suggested:
```js
'style-loader',
{loader: 'css-loader', options: {modules: true}},
```
This has worked well for projects without iframes.

Now I have a project where I have some normal content, and some content that needs to be inside an iframe.

I would like to be able to add this CSS into the iframe also.

If I remove 'style-loader' from my loader spec, I can add it to an iframe easily like so:

```jsx
import Frame from 'react-frame-component';
import css from './style.css';
export default () => <Frame><style>{css.toString()}</style>...<Frame>
```

When I do this, the `toString()` part does what I expect, but then I can't use the "css module" feature where `css.myClassName` gives me the randomized class name. Also, obviously, the css is not inserted into the main page.

If I _do_ include 'style-loader' in my loaders, I get the opposite set of things working: ie I can do `css.myClassName`, but not `css.toString()`;

My feature request: when `style-loader` runs after `css-loader`, please export css-loader's toString() so I can easily get the style on my page and inside my iframe.

### Feature Use Case
I want to include a particular CSS file in particular iframes in addition to having that CSS inserted into my page.
```jsx
import Frame from 'react-frame-component';
import pageOnlyCss from './pageOnly.css';
import css from './style.css';

export default () => (
    <div className={css.bordered}
        <h1>thing</h1>
        <Frame>
            <style>{css.toString()}</style>
            <div className={css.bordered}> ... </div>
        <Frame>
    </div>
);
```

### Workarounds?!

I suspect I can get something to work inside the iframe(s) by setting up separate webpack rules, and either copies of css files or maybe I can do it with sass includes or something.

I've also read ways of finding the <style> tag that has been created by style-loader and creating a duplicate for iframes. This sounds much more pleasant, but just doesn't cover the use case where I want to include a particular stylesheet in the iframe and not all of them.

Please post if you know of another workaround.

**Comment by JasonWoof** [comment]
oh, without `style-loader` I can access the class names via `css.locals.myClassName` instead of `css.myClassName`.

So my workaround can be to remove `style-loader`, use the move verbose syntax with `.locals` in it and insert the CSS into the document and iframe myself.

I still think this feature would be cool though, for people who want the css on the page automatically, and also want access to the css.

**Comment by evilebottnawi** [comment]
You want to implement `to-string-loader` in `style-loader`, we have same idea https://github.com/webpack-contrib/style-loader/issues/328#issuecomment-516437065, especial for shadow DOM

**Comment by evilebottnawi** [comment]
Let's close in favor https://github.com/webpack-contrib/style-loader/issues/328#issuecomment-516437065, feel free to feedback

**Comment by JasonWoof** [comment]
I don't understand. First can we make sure we're on the same page of what "css modules" are? When I google that I mostly get css-loader and the like. w3c calls 8-billion different spec documents "css modules" so it's tricky to find.

I found this though: https://github.com/w3c/webcomponents/blob/gh-pages/proposals/css-modules-v1-explainer.md

Is that what you're talking about?

As I understand it, that doesn't change the class names in the css (like css-loader does) but instead relies on browser support to isolate a portion of the dom that will be the only portion of the dom affected by that particular stylesheet.

That sounds cool, but it looks like it requires shadowsomething support, which doesn't have good browser support right now.

From what I can understand by reading your comment in #328, it sounds like you want to drop support for css-loader's global->local class name hash entirely, and that you want to export the css as text.

That would be a pretty big-deal breaking change.

I'm hoping you can serve the "w3c css module" without breaking the "css-loader css module" feature by just adding a `.toString()` method do your export that returns the css text.

**Comment by evilebottnawi** [comment]
> That sounds cool, but it looks like it requires shadowsomething support, which doesn't have good browser support right now.

**Comment by evilebottnawi** [comment]
> I'm hoping you can serve the "w3c css module" without breaking the "css-loader css module" feature by just adding a .toString() method do your export that returns the css text.

Yes, we don't want to change it on default value, we will implement option for this
