### ISSUE TITLE
entry csp nonce bug

### ISSUE THREAD

**Issue by joshxyzhimself** [webpack-contrib/style-loader#487]
### Environment

- os: Linux
- node 14.4.0
- webpack 4.44.2
- style-loader 1.2.1

### Expected Behavior

- following the csp nonce guide works at https://webpack.js.org/loaders/style-loader/#nonce

```js
// create-nonce.js

const csp_nonce = document.querySelector('meta[property=\'csp-nonce\']').getAttribute('content');
__webpack_nonce__ = csp_nonce;
```

```js
// entry.js

// this DOES get executed first
import './create-nonce.js';

// before this
import './style.css';
```

### Actual Behavior

- but then if we inline the `__webpack_nonce__` assignment in the entry, it acts weird

```js
// entry.js

// this DOES NOT get executed first
const csp_nonce = document.querySelector('meta[property=\'csp-nonce\']').getAttribute('content');
__webpack_nonce__ = csp_nonce;

// before this
import './style.css';

// which causes an error since __webpack_nonce__ is NOT SET
```

### How Do We Reproduce?

- can't produce a repro in a repo (lol that rhymes) because our implementation use internal stuff
- but the following are gists of our code 

```js
// webpack.config.js

        {
          test: /\.(css)$/,
          use: [
            { loader: 'style-loader' },
            { loader: 'css-loader', options: { importLoaders: 1 } },
            { loader: 'postcss-loader' },
          ],
        },

```

```js
// server response header CSP, with generated nonce from crypto.randomBytes(32).toString('base64')
// "http:" since we're testing locally

Content-Security-Policy: upgrade-insecure-requests; default-src http: 'self'; script-src http: 'nonce-lgp8w0DSKQSsv/s3//43EkM1GYyhkF0wHlzxWBUrW1s='; style-src http: 'nonce-lgp8w0DSKQSsv/s3//43EkM1GYyhkF0wHlzxWBUrW1s=';
```

```js
// html sent by server

<head>

        // loaded by create-nonce.js
        <meta property="csp-nonce" content="${nonce}">

        <style nonce="${nonce}">
          // inline style
        </style>
</head>

<body>
        // webpack chunks
        <script defer src="/scripts/${webpack_chunk}" nonce="${nonce}"></script>

        <script nonce="${nonce}">
          // inline scripts
        </script>
</body>
```

- possibly related to https://github.com/webpack-contrib/style-loader/issues/471

**Comment by joshxyzhimself** [comment]
- also possibly related to https://github.com/webpack-contrib/style-loader/issues/306

**Comment by evilebottnawi** [comment]
Sorry without reproducible test repo I will not help

**Comment by joshxyzhimself** [comment]
No worries, my understanding though is that all imports are executed first before all the other code in the entry script.

I think the order if imports is preserved, but not the order of the imports along with other code in a certain jsx file - in which case the imports always get executed first.

If that's the case, it's not really a bug with style-loader, maybe it's just how webpack-transpiled code works by design.

**Comment by alexander-akait** [comment]
Do you solve the problem?
