### ISSUE TITLE
Provide content hash to insert function

### ISSUE THREAD

**Issue by adi518** [webpack-contrib/style-loader#494]
- Operating System: `macOS`
- Node Version: `12.0.0`
- NPM Version: `6.14.8`
- webpack Version: `4.x`
- style-loader Version: `1.0.0`

### Feature Proposal
Provide a content hash argument to the `insert` function. This is useful for cases where manual caching is needed.

### Feature Use Case
Multiple applications loading to the same page, each within a shadow DOM, which requires a custom `insert` function. All styles need to be cached and attached to the `head` tag/each application (shadow host).

**Comment by alexander-akait** [comment]
It is impossible because content hash available only bundling

**Comment by alexander-akait** [comment]
and you don't need to use this approach, you need `string-loader` for this and insert styles in shadow dom

**Comment by adi518** [comment]
Can you link to that loader? there's a bunch of them and it seems hard to find.

**Comment by alexander-akait** [comment]
We have issue to implement this here + example with shadow dom, maybe I found time on this week to do it, we don't known content hash because module is processing and can be rewritten

**Comment by adi518** [comment]
I think Webpack has hooks to deal with that, so we can get the final code once all rewrites are done.

**Comment by alexander-akait** [comment]
> I think Webpack has hooks to deal with that, so we can get the final code once all rewrites are done.

No we can't, you don't provide code and what you want to achieve, so I can say you how to solve, but using content hash here is bad idea

**Comment by adi518** [comment]
Ok, I'll provide more context soon.

**Comment by adi518** [comment]
Here's a digram that portrays our needs:

![image](https://gist.githubusercontent.com/adi518/8ba075c346ed612351088f81036f24d7/raw/8b6489a8d68ef24757e4e147d83342ffea41709f/shadowDomStyleAttachmentDark.svg)

**Comment by adi518** [comment]
@alexander-akait Can you have a look at my diagram and hopefully propose a better way to achieve this? I have an idea to write `postcss` plugin that will prepend a content hash as a comment to each file, but I'm already running into an issue where the comment gets stripped out.

**Comment by alexander-akait** [comment]
Here example https://github.com/webpack-contrib/style-loader/blob/master/test/manual/src/custom-square.js, but here we need implement to-string export and insert value of import here https://github.com/webpack-contrib/style-loader/blob/master/test/manual/src/custom-square.js#L26, you should not use `head` for the shadow dom
