### ISSUE TITLE
Low performance when applyToSingletonTag

### ISSUE THREAD

**Issue by cenfun** [webpack-contrib/style-loader#496]
- Operating System: Windows
- Node Version: 14+
- NPM Version: 6+
- webpack Version: 5+
- style-loader Version:^2.0.0  latest

### Expected Behavior

high performance when load js in page

### Actual Behavior

![style-loader-low-performance](https://user-images.githubusercontent.com/334577/104557463-447e6680-567c-11eb-97d3-3722ccc1af6e.png)
1, big size css file with fonts or images
2, many of css files
3, injectType: singletonStyleTag

Low performance when calls addStyle -> applyToSingletonTag -> insertBefore 

DOM operations are very expensive, can we do only one last time insertBefore until all css content generated?

**Comment by alexander-akait** [comment]
> DOM operations are very expensive, can we do only one last time insertBefore until all css content generated?

What do you mean?

**Comment by cenfun** [comment]
close
