### ISSUE TITLE
Idea: Debounce adding of styles for better performance

### ISSUE THREAD

**Issue by jhnns** [webpack-contrib/style-loader#5]
I'm thinking about this issue quite a while but haven't found the time to write it down.

My co-worker was working on an app (without webpack) where he wanted to define style rules per component. These styles should only be applied if the component is currently in use, so he added and removed the style nodes accordingly.

While the theory is very nice, it has a serious performance impact. Because when a style node is added or removed the browser needs to recalculate all styles and to reflow the **whole** document. So when a page changed, the browser needed to recalculate and to reflow several times.

I was wondering if this problem could be solved by the style-loader. I was thinking about [debouncing](http://underscorejs.org/#debounce) the call where the `<style>` node is actually added to the DOM.

This feature needs to be tested carefully to avoid FOUTs (Flash of Unstyled Text) or other ugly problems when unstyled content is added to the DOM.

**Comment by michael-ciniawsky** [comment]
@jhnns @necolas @dashed Can this one be closed? Is `disable` still a considerable feature?

**Comment by jhnns** [comment]
It can be closed, but a note in the README would be good that the styles should be applied in batches when used in production (for instance via [fastdom](https://github.com/wilsonpage/fastdom)).
