### ISSUE TITLE
Minify the SCSS to CSS and inject it into DOM

### ISSUE THREAD

**Issue by rohitp-bsf** [webpack-contrib/style-loader#508]
Is it recommended to use style-loader in production mode? Also, I have implemented a style-loader in webpack and it works super perfectly but It loading with non minified version. Is there any way to minify the CSS and load it into the DOM?

**Comment by alexander-akait** [comment]
> Is it recommended to use style-loader in production mode?

Yes, you can use this loader in production.

> Is there any way to minify the CSS and load it into the DOM?

Using `postcss` (`postcss-loader`) and cssnano as plugin, we have an issue to improve this https://github.com/webpack-contrib/css-minimizer-webpack-plugin/issues/80,
