### ISSUE TITLE
TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by yelvert** [webpack-contrib/style-loader#517]
Module build failed (from ./node_modules/style-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (.../node_modules/style-loader/dist/index.js:18:24)

It looks like #501 dropped loader-utils as a dependency where this function came from, and instead tries to call this.getOptions which doesnt exist.

**Comment by milu2003** [comment]
How to solve it

**Comment by milu2003** [comment]
npm  i style-loader@2.0.0 -D

**Comment by alexander-akait** [comment]
You need webpack v5 to use the latest version of style-loader, please read changelog

**Comment by SantlyWinner** [comment]
> You need webpack v5 to use the latest version of style-loader, please read changelog

Thanks man, it helped me a lot! <3

**Comment by manoharmaddi** [comment]
./src/index.css
TypeError: this.getOptions is not a function

 i m getting this error  while executing please help me out

**Comment by anytodo92** [comment]
I am also getting  the issue above. how to solve issue?

**Comment by dep** [comment]
> I am also getting the issue above. how to solve issue?

take your laptop and throw it into the ocean.

seriously though, i have the same problem.

**Comment by markhowellsmead** [comment]
Have you read the comments above which show the solution?
