### ISSUE TITLE
Style-loader duplicates insert function

### ISSUE THREAD

**Issue by HuHguZ** [webpack-contrib/style-loader#518]
- Operating System: linux mint 20
- Node Version: v14.16.0
- NPM Version: 6.14.11
- webpack Version: 5.28.0
- css-loader Version: 3.0.0

### Expected Behavior

I expect that the style-loader will add the insert function to the bundle exactly 1 time.

### Actual Behavior

But in reality, this function is created for each css file and inserted as an expression, webpack cannot optimize it, because it thinks that these are different functions

![image](https://user-images.githubusercontent.com/32592443/124741224-25260f00-df24-11eb-8ca1-32d27ba92b0b.png)

### Code

```js
//css part of module.rules productuion config
{
    test: /\.css$/,
    exclude: /\.page\.css$/,
    use: [
      {
        loader: 'style-loader',
        options: {
          injectType: 'singletonStyleTag',
          insert: [Function: _insertCssIntoIframeImportedByStyleLoader]
        }
      },
      'css-modules-typescript-loader'
    ]
  },
  {
    test: /\.page\.css$/,
    use: [ 'style-loader', 'css-modules-typescript-loader' ]
  },
  {
    test: /\.css$/,
    use: [
      {
        loader: 'css-loader',
        options: {
          importLoaders: 1,
          modules: { localIdentName: '[hash:base64:5]' }
        }
      },
      'postcss-loader'
    ]
  }
```

**Comment by alexander-akait** [comment]
Partial fixed here https://github.com/webpack-contrib/style-loader/pull/520, anyway it is impossible to use custom function and include this only once, but we have solution `{ insert: require.resolve('./my-custom-style-function') }`, so you will not have multiple functions, WIP on this

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack-contrib/style-loader/pull/521, note you need to use `insert: require.resolve('./path/to/insert.js')` to allow reduce size of runtime

**Comment by HuHguZ** [comment]
thanks
