### ISSUE TITLE
HMR does not work with webpack 5

### ISSUE THREAD

**Issue by Yegorich555** [webpack-contrib/style-loader#523]
- Operating System: Windows 10
- Node Version: 14.15.0
- NPM Version: 6.14.8
- webpack Version: 5.44.0
- style-loader Version: 3.1.0

### Expected Behavior

HMR should work - should apply style-changes without reloading the page

### Actual Behavior

HMR doesn't work despite webpack see changed files and logs it into console

### Code

The whole configuration you can take a look here:
https://github.com/Yegorich555/webpack-must-have/tree/bug_hmr_styleLoader

### How Do We Reproduce?

1) Clone repo mentioned above
2) Run `npm i`
3) Run `npm run serve`
4) Try to change any line in any style-file (background color of h2 src/styles/main.css for example)
You can see that webpack logs changes in console but there are no updates related to styles in browser page (until I refresh page manually)

### Notes
I've tried rollback versions of style-loader but it didn't fix the case. Only rollback to webpack 4 resolves the issue

**Comment by alexander-akait** [comment]
Yep, here bug with `webpack-dev-server` v3 and webpack v5, you need to set `target: ['web']` (`target: ['web', 'es5']` if you need IE 11), we prepare webpack-dev-server v4, (hope, tomorrow I will do rc release, and stable on the next week) there it was fixed, sorry for this, sometimes it's not enough time to fix everything everywhere... Anyway feel free to feedback

**Comment by sh-a-v** [comment]
> 
> 
> Yep, here bug with `webpack-dev-server` v3 and webpack v5, you need to set `target: ['web']` (`target: ['web', 'es5']` if you need IE 11), we prepare webpack-dev-server v4, (hope, tomorrow I will do rc release, and stable on the next week) there it was fixed, sorry for this, sometimes it's not enough time to fix everything everywhere... Anyway feel free to feedback

Hmm
`target: ['web']` doesn't work
`target: 'web'` works

**Comment by alexander-akait** [comment]
oh, yes, `target: 'web'`, anyway in near future we will do good release, in our roadmap also caches and bundless mode for dev server for speedup
