### ISSUE TITLE
Changes to `insert` module file do not trigger cache invalidation

### ISSUE THREAD

**Issue by Mesoptier** [webpack-contrib/style-loader#526]
- Operating System: Ubuntu 20.04.2 LTS
- Node Version: v12.20.1
- ~NPM~ Yarn Version: 1.22.10
- webpack Version: 5.37.1
- style-loader Version: 3.1.0

### Expected Behavior

Changes to the module containing the `insert` function should be picked up by webpack and trigger cache invalidation.

### Actual Behavior

Changes to the module containing the function used for the `insert` option are not recognized by webpack, probably because the file is not added as a dependency. Instead, webpack keeps using the cached version.

### Code

```js
// webpack.config.js
{
    loader: 'style-loader',
    options: {
        insert: require.resolve('./insert.js'),
    }
}
```

```js
// insert.js
// Changes in this file do not invalidate the loader cache and so are not included in the build output
export default function insert(element) {
    // ...
}
```

### How Do We Reproduce?

1. Take a webpack project with persistent cache enabled and using style-loader where the ["Absolute path to function"](https://github.com/webpack-contrib/style-loader#absolute-path-to-function) is used for the `insert` option.
2. Build the project.
3. Add a `console.log` in `insert.js`.
4. Build the project again. Note that this build is much quicker since the cache is used.
5. The added `console.log` does not log anything in the browser, because it was not added to the build output.

---

This is probably an issue for the `styleTagTransform` option as well, since that uses the same system.

**Comment by Mesoptier** [comment]
Oops, I made a mistake! I thought my config applied style-loader for my `build` script, but of course it's only being applied in the `devserver` script. Since it works just fine in the DevServer script, I'll close this issue now :)

**Comment by alexander-akait** [comment]
anyway we have small bug here, we should add path to file in build dependencies, will be fixed today

**Comment by Mesoptier** [comment]
Isn't the path automatically added by webpack, since you're transpiling to `require`/`import` here?
https://github.com/webpack-contrib/style-loader/blob/6e70da0c5a37025510afe4f49ddeaf6c39daaa75/src/utils.js#L132-L138
