### ISSUE TITLE
i can't download the module

### ISSUE THREAD

**Issue by Liedsonrm** [webpack-contrib/style-loader#530]
### Actual Behavior

yarn add v1.22.11
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
error style-loader@3.2.1: The engine "node" is incompatible with this module. Expected version ">= 12.13.0". Got "10.19.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

### Code
```js
yarn add style-loader

**Comment by alexander-akait** [comment]
Please update Node.js locally, you need `>= 12.13.0` version
