### ISSUE TITLE
Is there a injectType=lazyStyleTag .use() & .unuse() equivalent when using css-loader + mini-css-extract-plugin

### ISSUE THREAD

**Issue by andy1547** [webpack-contrib/style-loader#554]
Documentation Is:

- [ X] Missing
- [ X] Needed
- [ X] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

We maintain a SPA that loads pages dynamically in response to hash state changes. For page routing, we use the "Dynamic expressions in import()" feature to import individual page chunks (each chunk consists of HTML, JS and LESS). To apply the page's specific less, we imports page-styles.less using injectType=lazyStyleTag and call.use() & .unuse() when the page is loaded & unloaded respectively (avoids CSS conflicts between individual pages). To apply the page's HTML, we insert/remove from a HTML container element.

We'd like the flexibility of using css-loader + mini-css-extract-plugin (without style-loader) for production builds. Is there another way of achieving the dynamic use/unuse functionality in webpack 5?
Perhaps there's some special syntax supported by html-loader that allows importing less files in HTML, resolving to either a \<link href=".css" rel="stylesheet"> tag in production mode (.css chunk file per page), or \<styles> tags in development. This works as a unuse() equivalent as the styling would be automatically removed when the HTML is removed from container element.

Secondly, is there a way to supply injectType=lazyStyleTag (either as configuration or inline option) to style-loader without renaming all .less to .lazy.less? We want the default for our non-lazy less files to be injectType=styleTag, so we're currently specifying verbosely as : 
````import styles from '!style-loader?injectType=lazyStyleTag!css-loader!less-loader!./styles.less';````

### Your Proposal for Changes

If the recommendation for production builds is not to use the style-loader, alternative dynamic css (loaded/unloaded on demand) strategies should be promoted over using style-loader's injectType=lazyStyleTag .use() & unuse().

If there's a cleaner way to import lazy styles (config or inline) without .less renames, please include details.

**Comment by alexander-akait** [comment]
No, when you use `mini-css-extract-plugin` you extract CSS as a file, so you need to write logic for loading on application side

**Comment by andy1547** [comment]
@alexander-akait thanks for your response.

As for the second question, adding .lazy a suffix to less/sass files isn't always possible (e.g. CSS sourced from npm packages). Is there a more concise way of loading with the style-loader on a per file basis without renaming to .less? Perhaps there's a way to suffix with .lazy in import statements but configure webpack to strip off the .lazy when resolving?

**Comment by alexander-akait** [comment]
You can set own `test` on any files and set any options, so files from node_modules will load as you want

**Comment by andy1547** [comment]
Sorry perhaps I wasn't clear enough in my question.

What's not obvious is how to tell webpack that a style import needs to be lazy loaded, when using either the inline loader option or changing the extension isn't an option (i.e. cannot rename from .less to .lazy.less).

````
// webpack.common.js
{
    test: /\.less$/i,
    use: [
        "style-loader",
        "css-loader",
        "less-loader",
    ],
    exclude: /\.lazy\.less$/i,
},
{
    test: /\.lazy\.less$/i,
    use: [
        { loader: "style-loader", options: { injectType: "lazyStyleTag" } },
        "css-loader",
        "less-loader",
    ],
},

// app.ts
import noneLazyStyles './css/styles.less';

// note this will give "Module not found: Error: Can't resolve './css/styles.lazy.less" error as file doesn't exist in disk.
import lazyStyles from './css/other-styles.lazy.less';

// apply style in response to user event (e.g. user enables custom css theme)
lazyStyles .use() / lazyStyles.unuse();
````

**Comment by alexander-akait** [comment]
You can use `query`, i.e. `import noneLazyStyles './css/styles.less?lazy';` using https://webpack.js.org/configuration/module/#ruleresourcequery

**Comment by andy1547** [comment]
Thanks for your response @alexander-akait .

Unfortunately the solution provided strangely reports a CSS syntax error:
````
ERROR in ./GlobalCss/bootstrap.css?lazy (./node_modules/css-loader/dist/cjs.js!./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./GlobalCss/bootstrap.css?lazy)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
CssSyntaxError

(2:7) C:\Project\SPA\GlobalCss\bootstrap.css Unknown word

  1 |
> 2 |       import API from "!../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
    |       ^
  3 |       import domAPI from "!../node_modules/style-loader/dist/runtime/styleDomAPI.js";
  4 |       import insertFn from "!../node_modules/style-loader/dist/runtime/insertBySelector.js";
 @ ./GlobalCss/bootstrap.css?lazy 10:6-188 12:10-17 12:21-35 13:32-46 33:17-24 47:0-158 47:0-158
 @ ./Scripts/app.ts 566:65-101 556:49-85
 @ ./Scripts/main.ts 41:0-34 55:34-42

--------------------------------------------------------------------

//app.ts
const bootstrap = await import(
	"GlobalCss/bootstrap.css?lazy") as { default: any; };
bootstrap.default.use();

--------------------------------------------------------------------

//webpack.common.js
{
	test: /\.less$/i,
	resourceQuery: /lazy/,
	use: [
		{ loader: "style-loader", options: { injectType: "lazyStyleTag" } },
		"css-loader",
		"less-loader",
	],
},            
{
	test: /\.less$/i,
	use: [
		"style-loader",
		"css-loader",
		"less-loader",
	],
},
{
	test: /\.css$/i,
	resourceQuery: /lazy/,
	use: [
		{ loader: "style-loader", options: { injectType: "lazyStyleTag" } },
		"css-loader",
	],
}, 
{
	test: /\.css$/i,
	use: [
		'style-loader', 
		'css-loader']
},
````
It seems like the resourceQuery is affecting the style-loader.

**Comment by alexander-akait** [comment]
As you can see you have invalid setup for loader

> ERROR in ./GlobalCss/bootstrap.css?lazy (./node_modules/css-loader/dist/cjs.js!./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./GlobalCss/bootstrap.css?lazy)

You apply css-loader on style-loader output, change order, that happens because you need set `resourceQuery: { not: /lazy/ },` for other loaders, otherwise you apply them twice

**Comment by zongzi531** [comment]
> Thanks for your response @alexander-akait.
> 
> Unfortunately the solution provided reports a CSS syntax error:
> 
> ```
> ERROR in ./GlobalCss/bootstrap.css?lazy (./node_modules/css-loader/dist/cjs.js!./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./GlobalCss/bootstrap.css?lazy)
> Module build failed (from ./node_modules/css-loader/dist/cjs.js):
> CssSyntaxError
> 
> (2:7) C:\Project\SPA\GlobalCss\bootstrap.css Unknown word
> 
>   1 |
> > 2 |       import API from "!../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
>     |       ^
>   3 |       import domAPI from "!../node_modules/style-loader/dist/runtime/styleDomAPI.js";
>   4 |       import insertFn from "!../node_modules/style-loader/dist/runtime/insertBySelector.js";
>  @ ./GlobalCss/bootstrap.css?lazy 10:6-188 12:10-17 12:21-35 13:32-46 33:17-24 47:0-158 47:0-158
>  @ ./App/app.ts 566:65-101 556:49-85
>  @ ./App/main.ts 41:0-34 55:34-42
> 
> --------------------------------------------------------------------
> 
> //app.ts
> // note, same error is reported for a static import at top of file when trying to use lazy styles, this example uses a dynamic import.
> const bootstrap = await import("GlobalCss/bootstrap.css?lazy") as { default: any; };
> bootstrap.default.use();
> 
> --------------------------------------------------------------------
> 
> //webpack.common.js
> {
> 	test: /\.less$/i,
> 	resourceQuery: /lazy/,
> 	use: [
> 		{ loader: "style-loader", options: { injectType: "lazyStyleTag" } },
> 		"css-loader",
> 		"less-loader",
> 	],
> },            
> {
> 	test: /\.less$/i,
> 	use: [
> 		"style-loader",
> 		"css-loader",
> 		"less-loader",
> 	],
> },
> {
> 	test: /\.css$/i,
> 	resourceQuery: /lazy/,
> 	use: [
> 		{ loader: "style-loader", options: { injectType: "lazyStyleTag" } },
> 		"css-loader",
> 	],
> }, 
> {
> 	test: /\.css$/i,
> 	use: [
> 		'style-loader', 
> 		'css-loader'
> 	]
> },
> ```
> 
> It seems like the resourceQuery is affecting the style-loader.

@andy1547 Hello, Can you tell me, how did you solve it?

**Comment by andy1547** [comment]
@zongzi531 To import LESS and CSS files, in a lazy and non-lazy fashion:
````
// lazy, need to call use / unuse on these
import lazyStyleA from "a.less?lazy";
import lazyStyleB from "b.css?lazy";
// none lazy imports, applied globally.
import "c.less";
import "d.css";
````
Webpack config required for this:
````
            {
                    test: /\.less$/i,
                    resourceQuery: /lazy/,
                    use: [
                        { loader: "style-loader", options: { injectType: "lazyStyleTag" } },
                        "css-loader",
                        "less-loader",
                    ],
                },            
                {
                    test: /\.less$/i,
                    resourceQuery: { not: /lazy/ },
                    use: [
                        "style-loader",
                        "css-loader",
                        "less-loader",
                    ],
                },
                {
                    test: /\.css$/i,
                    resourceQuery: /lazy/,
                    use: [
                        { loader: "style-loader", options: { injectType: "lazyStyleTag" } },
                        "css-loader",
                    ],
                }, 
                {
                    test: /\.css$/i,
                    resourceQuery: { not: /lazy/ },
                    use: [
                        'style-loader', 
                        'css-loader'
                    ]
                },
````

**Comment by zongzi531** [comment]
@andy1547 Thanks, It's strange that I encountered a schema validation error (`not`), it may be a version problem, but in the end I solved it in other ways.
