### ISSUE TITLE
why style-loader is pitch loader？

### ISSUE THREAD

**Issue by lzs246** [webpack-contrib/style-loader#567]
Hello
Excuse me, why style-loader is designed to be pitch loader?
I think can also get the result of css-loader in normal loader, and then insert the result into the style.
Is there any special situation, I didn't consider it?
Thank

**Comment by alexander-akait** [comment]
style-loader doesn't need to know which a loader was before, so it is pitch, we need only request

**Comment by lzs246** [comment]
Thanks a lot for answer
