### ISSUE TITLE
IE8 (and below): Replacing CSS containing @font-face results in "invisible" page

### ISSUE THREAD

**Issue by jerrysu** [webpack-contrib/style-loader#58]
I've been having issues with `style-loader` and IE8, which I've narrowed down to this line:
https://github.com/webpack/style-loader/blob/master/addStyles.js#L169

When a stylesheet containing `@font-face` is applied, a subsequent stylesheet causes the page to be rendered as "invisible". The page appears completely blank, but everything is there (you can see that the elements are there when using IE's DOM inspector).

This issue goes away when I do something like:

``` javascript
    if (!/@font-face/.test(css)) {
      styleElement.styleSheet.cssText = replaceText(index, css);
    }
```

But, of course, the stylesheet with `@font-face` isn't applied.

Googling the symptoms, I found:
https://github.com/keithclark/selectivizr/issues/30
http://stiankarlsen.me/blog/how-to-fix-selectivizr-in-ie8/

Which gives me a couple of things that I can try. I'll attempt to:

  1) load `@font-face` into a separate stylesheet (not in the `<head>`)
  2) parse the font URL and load it with a `<link>` (in the `<head>`)

I'll give this a shot and submit a PR if any of this works. Otherwise, if there is anything else I try or fallback to, I'd like to know.

**Comment by yargalot** [comment]
Got this issue today, would be great to get this in. :)

**Comment by michael-ciniawsky** [comment]
Closing alongside with the PR, bc of shutdown from the author
