### ISSUE TITLE
Disabling loaders does not work inside url()

### ISSUE THREAD

**Issue by syranide** [webpack-contrib/style-loader#75]
`background-image(!url!./file)` emits `Module not found: Error: Cannot resolve directory '.'` because it resolves to `./!url!./file`. Putting `require('!url!./file')` inside JS works just fine though, so I can only assume this is something wrong with style-loader?

**Comment by SpaceK33z** [comment]
Do you still have this issue with webpack v2?

**Comment by michael-ciniawsky** [comment]
@syranide Actually I would say this is `css-loader` rewriting URL's but I need more info on this, could you please provide your config and maybe a test repo fro reproduction proposes?

**Comment by syranide** [comment]
```
ERROR in ./~/css-loader?minimize&-restructuring&roundingPrecision=-1&compatibility=ie8!./src/style.css
Module not found: Error: Cannot resolve directory '.' in /.../src
 @ ./~/css-loader?minimize&-restructuring&roundingPrecision=-1&compatibility=ie8!./src/style.css 6:10813-10858
```

Unfortunately I don't have the time to debug this further right now (and we're still on Webpack 1), but I can confirm it still appears to be happening as above. These are the relevant parts of the config I think:

```
        {
          test: /\.css$/,
          include: __dirname + '/src',
          exclude: /\.module\.css$/,
          loaders: [
            'style/useable',
            'css' +
              '?minimize' +
              '&-restructuring' +
              '&roundingPrecision=-1' +
              '&compatibility=ie8'
          ]
        },
...
        {
          test: /\.(gif|png|jpg|swf|ttf|eot|woff)$/,
          loaders: [
            'file' +
              '?name=[sha512:hash:base62:12].[ext]'
          ]
        }
```

**Comment by michael-ciniawsky** [comment]
> ERROR in ./~/**css-loader**?minimize&-restructuring&roundingPrecision=-1&compatibility=ie8!./src/style.css

This seems to be and I'm pretty sure it is a `css-loader` issue, please reopen at `css-loader`with the loader version in use. The '.' smells like `query.root` bug there, we have some of these @css-loader already and fix is underway, but unlikely for webpack v1 😛
