### ISSUE TITLE
Compiled code throwing Uncaught TypeError: p.use is not a function

### ISSUE THREAD

**Issue by sap9433** [webpack-contrib/style-loader#81]
though `styles.use()` , `styles.unuse()`  works perfectly in webPackDevServer . But after running bundler in bundled file these style-loader functions `use` , `unuse`, `ref`, `unref` is undefined.

**Comment by SpaceK33z** [comment]
Do you still have this issue?

**Comment by michael-ciniawsky** [comment]
@sap9433 Still getting this error with the latest `style-loader`? In need more info on this (`webpack.config.js`, `package.json`, webpack && webpack.dev-server versions) etc

**Comment by michael-ciniawsky** [comment]
@sap9433 If you still have this regression, see the previous comments and feel free to reopen 😛
