### ISSUE TITLE
Cast a DOM event when all style tags are injected

### ISSUE THREAD

**Issue by phaistonian** [webpack-contrib/style-loader#83]
I am sure this could be done the "tricky" way, but how about having it in-place natively?

That would/could come in handy in many use-cases, e.g get a new getBoundingClientRect().

**Comment by faddee** [comment]
+1

**Comment by weotch** [comment]
:+1:

**Comment by elektronik2k5** [comment]
+1

**Comment by jetpacmonkey** [comment]
Any possibility that this gets done?

**Comment by krazi3** [comment]
+1

**Comment by phaistonian** [comment]
I did it a while back using `MutationObserver`.

Nothing fancy, but I'd definitely prefer it would be provided "natively".

**Comment by michael-ciniawsky** [comment]
@phaistonian can you propose a way to do/add it in `style-loader` or even better send a PR 😛 ?

**Comment by phaistonian** [comment]
The following snippet illustrated the way I do it.

Works like a charm, but it's far from ideal -- I am guessing :)

In any case, `MutationObserver` is the way to do it in my case, however since this is not supported by legacy systems, one has to deal with the DOM events too.

Perhaps, "this" could point somewhere :)

```js
import throttle from 'throttleit';

let observer;

function loaded () {
  setTimeout(() => {
    const myEvent = new CustomEvent('webpackReady');
    window.dispatchEvent(myEvent);

    window.webpackIsLoaded = true;
  }, 500);

  // Just once, please
  observer.disconnect();
}

function init () {
  const target = document.head;
  const debouncer = throttle(loaded, 50);
  let isTriggered = false;

  observer = new MutationObserver(mutations => {
    mutations.forEach(mutation => {
      if (isTriggered) {
        return;
      }

      if (mutation.addedNodes.length) {
        isTriggered = true;
        debouncer();
      }
    });
  });

  const config = { characterData: true, childList: true };

  observer.observe(target, config);
}

if (window.ENV.environment === 'local' && window.MutationObserver) {
  init();
} else {
  window.webpackIsLoaded = true;
}
```

**Comment by d3viant0ne** [comment]
`Adds CSS to the DOM by injecting a <style> tag`

This feature, regardless of it's utility doesn't belong in `style-loader`. IMO if the functionality is that useful, a new loader should be created to accomplish this task and then chain them.

**Comment by bebraw** [comment]
Yeah, a separate loader would work better.
