### ISSUE TITLE
Is this loader maintained?

### ISSUE THREAD

**Issue by Strate** [webpack-contrib/style-loader#98]
No responses for issues, no responses for PR. Is it alive?

**Comment by satazor** [comment]
@sokra I think you are overwhelmed with work. Perhaps you should do a call for help?

**Comment by sokra** [comment]
help...

**Comment by satazor** [comment]
@sokra I mean, you could write a simple blogpost explaining the current situation of webpack and its modules and where help is most needed. I'm sure a lot of people would be interested in helping you maintaining it. People that were overwhelmed have done the same in the past, such as @visionmedia & @sindresorhus and the community was very responsive. I'm sure that @ryanflorence could also help get the word spread out.

**Comment by ttbarnes** [comment]
There doesn't seem to be an alternative to style-loader either. We may have to re-structure an entire large project purely because of style-loader issues. We are unable to run karma unit tests on components that utilise style-loader - not good (#100).

**Comment by michael-ciniawsky** [comment]
> Is this loader maintained? 

Yep :stuck
